=== albfan/jEdit/trunk/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | LITERAL1 | LITERAL2
	| LABEL | KEYWORD1 | KEYWORD2 | KEYWORD3 | FUNCTION
	| MARKUP | OPERATOR | DIGIT | INVALID )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-standard-mix 'TYPE %tokens; "NULL"
	AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( TERMINATE | SEQ | SEQ_REGEXP | SPAN | SPAN_REGEXP
	| EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-standard-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-standard-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-standard-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-standard-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ELEMENT END ( #PCDATA ) >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-standard-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-standard-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-standard-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-standard-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS ( NULL | COMMENT1 | COMMENT2 | LITERAL1 | LITERAL2
	| LABEL | KEYWORD1 | KEYWORD2 | KEYWORD3 | FUNCTION | MARKUP
	| OPERATOR | DIGIT | INVALID )+ >

<!-- KEYWORDS children -->
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== albfan/jEdit/trunk/modes/jamon.xml
<?xml version="1.0"?>
<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- Mode file for Jamon templates. See http://www.jamon.org -->
<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;%--" />
		<PROPERTY NAME="commentEnd" VALUE="--%&gt;" />
	</PROPS>
	<RULES IGNORE_CASE="FALSE" DEFAULT="LITERAL2">
		<SPAN_REGEXP HASH_CHAR="&lt;" MATCH_TYPE="OPERATOR" DELEGATE="java::MAIN">
			<BEGIN>&lt;%(args|class|import|java|xargs)&gt;</BEGIN>
			<END>&lt;/%$1&gt;</END>
		</SPAN_REGEXP>
		<SPAN_REGEXP HASH_CHAR="&lt;" MATCH_TYPE="OPERATOR" DELEGATE="java::MAIN">
			<BEGIN>&lt;%(?:if|for|java)</BEGIN>
			<END>%&gt;</END>
		</SPAN_REGEXP>
		<SEQ_REGEXP HASH_CHAR="&lt;" TYPE="OPERATOR">&lt;/%(?:if|for)&gt;</SEQ_REGEXP>
		<SEQ TYPE="OPERATOR">&lt;%else&gt;</SEQ>

		<SPAN_REGEXP HASH_CHAR="&lt;" MATCH_TYPE="OPERATOR" TYPE="KEYWORD2">
			<BEGIN>&lt;%(?:abstract|def|doc|escape|extends|frag|method|override)</BEGIN>
			<END>&gt;</END>
		</SPAN_REGEXP>
		<SPAN_REGEXP HASH_CHAR="&lt;" MATCH_TYPE="OPERATOR">
			<BEGIN>&lt;/%(?:def|doc|frag|method|override)</BEGIN>
			<END>&gt;</END>
		</SPAN_REGEXP>

		<SPAN TYPE="OPERATOR" DELEGATE="java::MAIN">
			<BEGIN>&lt;%</BEGIN>
			<END>%&gt;</END>
		</SPAN>

		<SPAN_REGEXP HASH_CHAR="&lt;" MATCH_TYPE="OPERATOR" DELEGATE="java::MAIN">
			<BEGIN>&lt;&amp;\|?</BEGIN>
			<END>&amp;&gt;</END>
		</SPAN_REGEXP>
		<SEQ TYPE="OPERATOR">&lt;/&amp;&gt;</SEQ>

		<!-- JavaScript -->
		<SPAN_REGEXP TYPE="MARKUP" HASH_CHAR="&lt;" DELEGATE="JAVASCRIPT">
			<BEGIN>&lt;(?i)(script)</BEGIN>
			<END>&lt;/$1&gt;</END>
		</SPAN_REGEXP>

		<!-- Override HTML tag parsing to special-case attribute values. -->
		<SPAN TYPE="MARKUP" DELEGATE="TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<IMPORT DELEGATE="html::MAIN"/>
	</RULES>

	<RULES SET="JAVASCRIPT" DEFAULT="LITERAL1">
		<SPAN TYPE="OPERATOR" DELEGATE="java::MAIN">
			<BEGIN>&lt;%</BEGIN>
			<END>%&gt;</END>
		</SPAN>
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE" ESCAPE="\" DELEGATE="LITERAL">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<IMPORT DELEGATE="javascript::MAIN" />
	</RULES>

	<RULES SET="TAGS" DEFAULT="LITERAL1">
		<SPAN TYPE="LITERAL1" DELEGATE="LITERAL">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<IMPORT DELEGATE="html::TAGS" />
	</RULES>

	<RULES SET="LITERAL" DEFAULT="LITERAL1">
		<SPAN TYPE="OPERATOR" DELEGATE="java::MAIN">
			<BEGIN>&lt;%</BEGIN>
			<END>%&gt;</END>
		</SPAN>
	</RULES>

</MODE>

=== albfan/jEdit/trunk/modes/assembly-ags.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- Apollo Guidance Computer (AGC) Assembly mode by Jim Lawton (jim DOT lawton AT gmail DOT com). -->

<MODE>

	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="#" />
	</PROPS>

	<RULES HIGHLIGHT_DIGITS="TRUE" IGNORE_CASE="TRUE">
		<EOL_SPAN TYPE="COMMENT2">##</EOL_SPAN>
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>

		<MARK_PREVIOUS TYPE="LABEL" MATCH_TYPE="OPERATOR"
			AT_LINE_START="TRUE">&#09;</MARK_PREVIOUS>

		<!-- Binary Operators -->
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>

		<KEYWORDS>
			<!-- Directives -->
			<KEYWORD1>ORG</KEYWORD1> 
			<KEYWORD1>BSS</KEYWORD1> 
			<KEYWORD1>BES</KEYWORD1> 
			<KEYWORD1>SYN</KEYWORD1> 
			<KEYWORD1>EQU</KEYWORD1> 
			<KEYWORD1>DEFINE</KEYWORD1> 
			<KEYWORD1>DEC</KEYWORD1> 
			<KEYWORD1>OCT</KEYWORD1> 
			<KEYWORD1>END</KEYWORD1>

			<!-- Registers -->
			<KEYWORD3>A</KEYWORD3>
			<KEYWORD3>Q</KEYWORD3>
			<KEYWORD3>INDEX</KEYWORD3>

			<!-- Opcodes -->
			<FUNCTION>ABS</FUNCTION>
			<FUNCTION>ADD</FUNCTION> 
			<FUNCTION>ADZ</FUNCTION> 
			<FUNCTION>ALS</FUNCTION> 
			<FUNCTION>AXT</FUNCTION> 
			<FUNCTION>CLA</FUNCTION> 
			<FUNCTION>CLZ</FUNCTION> 
			<FUNCTION>COM</FUNCTION> 
			<FUNCTION>DLY</FUNCTION> 
			<FUNCTION>DVP</FUNCTION> 
			<FUNCTION>INP</FUNCTION> 
			<FUNCTION>LDQ</FUNCTION> 
			<FUNCTION>LLS</FUNCTION> 
			<FUNCTION>LRS</FUNCTION> 
			<FUNCTION>MPR</FUNCTION> 
			<FUNCTION>MPY</FUNCTION> 
			<FUNCTION>MPZ</FUNCTION> 
			<FUNCTION>OUT</FUNCTION>
			<FUNCTION>STO</FUNCTION> 
			<FUNCTION>STQ</FUNCTION> 
			<FUNCTION>SUB</FUNCTION> 
			<FUNCTION>SUZ</FUNCTION> 
			<FUNCTION>TIX</FUNCTION> 
			<FUNCTION>TMI</FUNCTION> 
			<FUNCTION>TOV</FUNCTION> 
			<FUNCTION>TRA</FUNCTION> 
			<FUNCTION>TSQ</FUNCTION> 

		</KEYWORDS>
	</RULES>
</MODE>

=== albfan/jEdit/trunk/modes/4gl.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="{" />
		<PROPERTY NAME="commentEnd" VALUE="}" />
		<PROPERTY NAME="lineComment" VALUE="--" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- 4GL style comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>
		<EOL_SPAN TYPE="COMMENT2">#</EOL_SPAN>
		<EOL_SPAN TYPE="COMMENT2">--</EOL_SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<!-- preprocessor statements -->

		<EOL_SPAN TYPE="COMMENT1">//</EOL_SPAN>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>

		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">||</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<SEQ TYPE="NULL">:</SEQ>

		<!-- Function calls -->
		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<KEYWORDS IGNORE_CASE="TRUE">
			<KEYWORD3>char</KEYWORD3>
			<KEYWORD3>double</KEYWORD3>
			<KEYWORD3>float</KEYWORD3>
			<KEYWORD3>int</KEYWORD3>
			<KEYWORD3>integer</KEYWORD3>
			<KEYWORD3>smallint</KEYWORD3>
			<KEYWORD3>long</KEYWORD3>
			<KEYWORD3>short</KEYWORD3>
			<KEYWORD3>decimal</KEYWORD3>
			<KEYWORD3>money</KEYWORD3>
			<KEYWORD3>record</KEYWORD3>
			<KEYWORD3>like</KEYWORD3>

			<KEYWORD1>begin</KEYWORD1>
			<KEYWORD1>rollback</KEYWORD1>
			<KEYWORD1>commit</KEYWORD1>
			<KEYWORD1>work</KEYWORD1>
			<KEYWORD1>call</KEYWORD1>
			<KEYWORD1>sleep</KEYWORD1>
			<KEYWORD1>whenever</KEYWORD1>
			  <KEYWORD1>error</KEYWORD1>
			    <KEYWORD1>continue</KEYWORD1>
			    <KEYWORD1>stop</KEYWORD1>
			<KEYWORD1>clear</KEYWORD1>
			  <KEYWORD1>screen</KEYWORD1>
			<KEYWORD1>function</KEYWORD1>
			<KEYWORD1>let</KEYWORD1>
			<KEYWORD1>construct</KEYWORD1>
			<KEYWORD1>declare</KEYWORD1>
			<KEYWORD1>execute</KEYWORD1>
			<KEYWORD1>free</KEYWORD1>
			<KEYWORD1>prepare</KEYWORD1>
			<KEYWORD1>database</KEYWORD1>
			<KEYWORD1>define</KEYWORD1>
			<KEYWORD1>foreach</KEYWORD1>
			<KEYWORD1>message</KEYWORD1>
			<KEYWORD1>exit</KEYWORD1>
			<KEYWORD1>report</KEYWORD1>
			<KEYWORD1>start</KEYWORD1>
			<KEYWORD1>prompt</KEYWORD1>
			<KEYWORD1>main</KEYWORD1>
			<KEYWORD1>globals</KEYWORD1>
			<KEYWORD1>finish</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>open</KEYWORD1>
			<KEYWORD1>close</KEYWORD1>
			<KEYWORD1>window</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>goto</KEYWORD1>
			<KEYWORD1>end</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>then</KEYWORD1>
			<KEYWORD1>display</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>prepare</KEYWORD1>
			<KEYWORD1>cursor</KEYWORD1>
			<KEYWORD1>select</KEYWORD1>
			<KEYWORD1>insert</KEYWORD1>
			<KEYWORD1>where</KEYWORD1>
			<KEYWORD1>into</KEYWORD1>
			<KEYWORD1>order</KEYWORD1>
			<KEYWORD1>program</KEYWORD1>
			<KEYWORD1>print</KEYWORD1>
			<KEYWORD1>column</KEYWORD1>
			<KEYWORD1>from</KEYWORD1>

			<KEYWORD2>with</KEYWORD2>
			<KEYWORD2>form</KEYWORD2>
			<KEYWORD2>at</KEYWORD2>
			<KEYWORD2>not</KEYWORD2>
			<KEYWORD2>matches</KEYWORD2>
			<KEYWORD2>today</KEYWORD2>
			<KEYWORD2>current</KEYWORD2>
			<KEYWORD2>noentry</KEYWORD2>
			<KEYWORD2>clipped</KEYWORD2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>false</LITERAL2>
			<LITERAL2>null</LITERAL2>
			<LITERAL2>sqlca.sqlcode</LITERAL2>
		</KEYWORDS>
	</RULES>
</MODE>

=== albfan/jEdit/trunk/modes/factor.xml
<?xml version="1.0"?>
<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="indentOpenBrackets" VALUE="["/>
		<PROPERTY NAME="indentCloseBrackets" VALUE="]"/>
		<PROPERTY NAME="lineUpClosingBracket" VALUE="true"/>
		<PROPERTY NAME="indentNextLines" VALUE="^(\*<<|:).*"/>
		<PROPERTY NAME="doubleBracketIndent" VALUE="true"/>
		<PROPERTY NAME="commentStart" VALUE="("/>
		<PROPERTY NAME="commentEnd" VALUE=")"/>
		<PROPERTY NAME="lineComment" VALUE="!"/>
	</PROPS>
	<RULES IGNORE_CASE="FALSE" ESCAPE="\" NO_WORD_SEP="+-*=><;.?">
		<EOL_SPAN TYPE="COMMENT4">!!!</EOL_SPAN>
		<EOL_SPAN TYPE="COMMENT2">#!</EOL_SPAN>
		<EOL_SPAN TYPE="COMMENT1">!</EOL_SPAN>

		<!-- colon definitions -->
		<SEQ_REGEXP TYPE="MARKUP" HASH_CHAR=":">:\s+(\S+)</SEQ_REGEXP>
		
		<SPAN TYPE="COMMENT3">
			<BEGIN>( </BEGIN>
			<END>)</END>
		</SPAN>
		<SPAN NO_ESCAPE="TRUE" TYPE="LITERAL1">
			<BEGIN>#"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="INVALID">
			<BEGIN>#&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<KEYWORDS>
			<OPERATOR>[</OPERATOR>
			<OPERATOR>]</OPERATOR>
			<OPERATOR>|</OPERATOR>

			<MARKUP>;</MARKUP>

			<LABEL>~&lt;&lt;</LABEL>
			<LABEL>--</LABEL>
			<LABEL>&gt;&gt;~</LABEL>

			<LITERAL1>t</LITERAL1>
			<LITERAL3>f</LITERAL3>
		</KEYWORDS>

	</RULES>
</MODE>

=== albfan/jEdit/trunk/modes/coffeescript.xml
<?xml version="1.0"?>
<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- CoffeeScript mode by Dennis Hotson, Balazs Toth

Beta

TODO:
- reconsider (un)indentation rules for brackets
-->
<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="###" />
		<PROPERTY NAME="commentEnd" VALUE="###" />
		<PROPERTY NAME="lineComment" VALUE="#" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />

		<!-- Auto indent -->
		<PROPERTY NAME="indentNextLines"
			VALUE="((\s*|.*\s+)([\-=]&gt;|[\+\-\*/%\\&lt;&gt;=\!&amp;\|\^~]|(.*:|&lt;&lt;|&gt;&gt;|&gt;&gt;&gt;|\+=|\-=|\*=|/=|%=|&lt;=|&gt;=|==|===|\!=|\!==|is|isnt|not|and|or|&amp;&amp;|\|\||of|in))|\s*(if|else|try|catch|finally|class|while|until|for)(\s*|\s+.*))\s*" />

		<PROPERTY NAME="unindentThisLine"  VALUE="^\s*(else|catch|finally)(\s*|\s+.*)$" />
		<PROPERTY NAME="unindentNextLines" VALUE="^\s*(else|catch|finally)(\s*|\s+.*)$" />

		<!-- Props regarding brackets generally do not play well with CoffeScript -->

		<!-- Triggers reindentation on character input.
		TODO: reconsider the use of this one, including "ehy" -->
		<!-- PROPERTY NAME="electricKeys" VALUE="}])" /-->

		<!-- Originally designed for Python, does not work correctly with CS -->
		<!-- PROPERTY NAME="ignoreWhitespace" VALUE="false" /-->
	</PROPS>

	<RULES
		IGNORE_CASE="FALSE"
		HIGHLIGHT_DIGITS="TRUE"
		DIGIT_RE="(0[xX][0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?([eE][+\-]?[0-9]+)?)">

		<SPAN TYPE="COMMENT2">
			<BEGIN>###</BEGIN>
			<END>###</END>
		</SPAN>
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="FALSE" ESCAPE="\" DELEGATE="doubleQuoteLiteral">
			<BEGIN>"""</BEGIN>
			<END>"""</END>
		</SPAN>

		<SPAN TYPE="LITERAL2" NO_LINE_BREAK="FALSE" ESCAPE="\">
			<BEGIN>'''</BEGIN>
			<END>'''</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="FALSE" ESCAPE="\" DELEGATE="doubleQuoteLiteral">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL2" NO_LINE_BREAK="FALSE" ESCAPE="\">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" DELEGATE="javascript::MAIN">
			<BEGIN>`</BEGIN>
			<END>`</END>
		</SPAN>

		<!-- Javascript-style regexps -->
		<SEQ_REGEXP TYPE="MARKUP">(?&lt;!\d)\s*/(?![\s/*+{}?]).*/[igmy]*</SEQ_REGEXP>
		<!-- Heregexps -->
		<SPAN TYPE="MARKUP" DELEGATE="hereRegexp">
			<BEGIN>///</BEGIN>
			<END>///</END>
		</SPAN>

		<MARK_PREVIOUS TYPE="FUNCTION" MATCH_TYPE="OPERATOR">(</MARK_PREVIOUS>
		<!-- Seems to be equivalent to
		SEQ_REGEXP TYPE="FUNCTION">([a-zA-Z\$_](\w|\$)*)(?=\s*\()</SEQ_REGEXP -->

		<SEQ TYPE="OPERATOR">)</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">[</SEQ>
		<SEQ TYPE="OPERATOR">]</SEQ>
		<SEQ TYPE="OPERATOR">.</SEQ>

		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">\</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">:</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">;</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">?</SEQ>

		<SEQ_REGEXP TYPE="KEYWORD3">@([a-zA-Z\$_](\w|\$)*)</SEQ_REGEXP>
		<SEQ_REGEXP TYPE="KEYWORD4">([a-zA-Z\$_](\w|\$)*)(?=\s*[:\.])</SEQ_REGEXP>

		<KEYWORDS>
			<KEYWORD3>this</KEYWORD3>
			<KEYWORD3>super</KEYWORD3>

			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>new</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>try</KEYWORD1>
			<KEYWORD1>catch</KEYWORD1>
			<KEYWORD1>finally</KEYWORD1>
			<KEYWORD1>throw</KEYWORD1>
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>delete</KEYWORD1>
			<KEYWORD1>instanceof</KEYWORD1>
			<KEYWORD1>typeof</KEYWORD1>
			<KEYWORD1>switch</KEYWORD1>
			<KEYWORD1>extends</KEYWORD1>
			<KEYWORD1>class</KEYWORD1>
			<KEYWORD1>constructor</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>function</KEYWORD1>
			<KEYWORD1>var</KEYWORD1>
			<KEYWORD1>void</KEYWORD1>
			<KEYWORD1>with</KEYWORD1>
			<KEYWORD1>const</KEYWORD1>
			<KEYWORD1>let</KEYWORD1>
			<KEYWORD1>enum</KEYWORD1>
			<KEYWORD1>export</KEYWORD1>
			<KEYWORD1>import</KEYWORD1>
			<KEYWORD1>native</KEYWORD1>
			<KEYWORD1>then</KEYWORD1>
			<KEYWORD1>unless</KEYWORD1>
			<KEYWORD1>until</KEYWORD1>
			<KEYWORD1>of</KEYWORD1>
			<KEYWORD1>by</KEYWORD1>
			<KEYWORD1>where</KEYWORD1>
			<KEYWORD1>when</KEYWORD1>

			<KEYWORD1>and</KEYWORD1>
			<KEYWORD1>or</KEYWORD1>
			<KEYWORD1>not</KEYWORD1>
			<KEYWORD1>is</KEYWORD1>
			<KEYWORD1>isnt</KEYWORD1>

			<KEYWORD3>prototype</KEYWORD3>
			<KEYWORD3>Array</KEYWORD3>
			<KEYWORD3>Boolean</KEYWORD3>
			<KEYWORD3>Date</KEYWORD3>
			<KEYWORD3>Function</KEYWORD3>
			<KEYWORD3>Global</KEYWORD3>
			<KEYWORD3>Math</KEYWORD3>
			<KEYWORD3>Number</KEYWORD3>
			<KEYWORD3>Object</KEYWORD3>
			<KEYWORD3>RegExp</KEYWORD3><!-- Not ECMA -->
			<KEYWORD3>String</KEYWORD3>

			<!-- Literals -->
			<LITERAL2>false</LITERAL2>
			<LITERAL2>null</LITERAL2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>yes</LITERAL2>
			<LITERAL2>no</LITERAL2>
			<LITERAL2>on</LITERAL2>
			<LITERAL2>off</LITERAL2>
			<LITERAL2>NaN</LITERAL2>
			<LITERAL2>Infinity</LITERAL2>

			<!-- Global functions -->
			<LITERAL2>eval</LITERAL2>
			<LITERAL2>parseInt</LITERAL2>
			<LITERAL2>parseFloat</LITERAL2>
			<LITERAL2>escape</LITERAL2>
			<LITERAL2>unescape</LITERAL2>
			<LITERAL2>isNaN</LITERAL2>
			<LITERAL2>isFinite</LITERAL2>
		</KEYWORDS>
	</RULES>

	<!-- Delegate contents of #{} expression in double quotes to MAIN so that
	     it will be syntax highlighted as well -->
	<RULES DEFAULT="LITERAL1" SET="doubleQuoteLiteral" ESCAPE="\">
		<SPAN DELEGATE="MAIN" TYPE="OPERATOR">
			<BEGIN>#{</BEGIN>
			<END>}</END>
		</SPAN>
	</RULES>

	<!-- Comments in heregexes -->
	<RULES DEFAULT="MARKUP" SET="hereRegexp" ESCAPE="\">
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>
	</RULES>

</MODE>

=== albfan/jEdit/trunk/modes/freemarker.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- A JEdit mode configuration file for FTL (FreeMarker Template Language) 
     Note that this version will only work with JEdit 4.1pre6 or later. -->

<MODE>
  <RULES IGNORE_CASE="FALSE">

    <!-- JavaScript -->
    <SPAN TYPE="MARKUP" DELEGATE="html::JAVASCRIPT">
    <BEGIN>&lt;script</BEGIN>
    <END>&lt;/script&gt;</END>
    </SPAN>
    <SPAN TYPE="MARKUP" DELEGATE="html::JAVASCRIPT">
    <BEGIN>&lt;Script</BEGIN>
    <END>&lt;/Script&gt;</END>
    </SPAN>
    <SPAN TYPE="MARKUP" DELEGATE="html::JAVASCRIPT">
    <BEGIN>&lt;SCRIPT</BEGIN>
    <END>&lt;/SCRIPT&gt;</END>
    </SPAN>

    <!-- stylesheet -->
    <SPAN TYPE="MARKUP" DELEGATE="html::CSS">
    <BEGIN>&lt;style</BEGIN>
    <END>&lt;/style&gt;</END>
    </SPAN>
    <SPAN TYPE="MARKUP" DELEGATE="html::CSS">
    <BEGIN>&lt;Style</BEGIN>
    <END>&lt;/Style&gt;</END>
    </SPAN>
    <SPAN TYPE="MARKUP" DELEGATE="html::CSS">
    <BEGIN>&lt;STYLE</BEGIN>
    <END>&lt;/STYLE&gt;</END>
    </SPAN>

    <!-- XML/HTML comment -->
    <SPAN TYPE="COMMENT2" DELEGATE="xml::DTD-TAGS">
    <BEGIN>&lt;!--</BEGIN>
    <END>--&gt;</END>
    </SPAN>

    <!-- DTD instructions -->
    <SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
    <BEGIN>&lt;!</BEGIN>
    <END>&gt;</END>
    </SPAN>

    <!-- FTL markup starts here. -->

    <SPAN TYPE="KEYWORD1" DELEGATE="EXPRESSION">
      <BEGIN>${</BEGIN>
      <END>}</END>
    </SPAN>

    <SPAN TYPE="KEYWORD1" DELEGATE="EXPRESSION">
      <BEGIN>#{</BEGIN>
      <END>}</END>
    </SPAN>

    <SPAN_REGEXP TYPE="KEYWORD1" HASH_CHAR="&lt;" DELEGATE="EXPRESSION">
      <BEGIN>&lt;#ftl\&gt;</BEGIN>
      <END>&gt;</END>
    </SPAN_REGEXP>
    
    <!-- Is it really necessary to have 2 SPAN_REGEXP elements here? Kludgy... -->
    <SPAN_REGEXP TYPE="KEYWORD1" DELEGATE="EXPRESSION" HASH_CHAR="&lt;">
      <BEGIN>&lt;#?(if|elseif|switch|foreach|list|case|assign|local|global|include|stop|escape|macro|function|transform|call)\s</BEGIN>
      <END>&gt;</END>
    </SPAN_REGEXP>
    <SPAN_REGEXP TYPE="KEYWORD1" DELEGATE="EXPRESSION" HASH_CHAR="&lt;">
      <BEGIN>&lt;#?(if|elseif|switch|foreach|list|case|assign|local|global|include|stop|escape|macro|function|transform|call)$</BEGIN>
      <END>&gt;</END>
    </SPAN_REGEXP>


    <SPAN_REGEXP TYPE="KEYWORD1" DELEGATE="INVALID" HASH_CHAR="&lt;">
      <BEGIN>&lt;/#?(if|switch|foreach|list|escape|macro|function|transform|compress|noescape)\&gt;</BEGIN>
      <END>&gt;</END>
    </SPAN_REGEXP>
    <SPAN_REGEXP TYPE="KEYWORD1" DELEGATE="INVALID" HASH_CHAR="&lt;">
      <BEGIN>&lt;#?(else|compress|noescape|default|break|flush|return)\&gt;</BEGIN>
      <END>&gt;</END>
    </SPAN_REGEXP>
    
    <SPAN TYPE="COMMENT1">
      <BEGIN>&lt;#--</BEGIN>
      <END>--&gt;</END>
    </SPAN>

    <SEQ TYPE="KEYWORD1">&lt;stop&gt;</SEQ>
     <SPAN TYPE="COMMENT1">
    <BEGIN>&lt;comment&gt;</BEGIN>
    <END>&lt;/comment&gt;</END>
    </SPAN>
    <SPAN TYPE="INVALID">
      <BEGIN>&lt;#</BEGIN>
      <END>&gt;</END>
    </SPAN>
    <SPAN TYPE="INVALID">
      <BEGIN>&lt;/#</BEGIN>
      <END>&gt;</END>
    </SPAN>

    <!-- non-FTL markup -->
    <SPAN TYPE="MARKUP" DELEGATE="TAGS">
    <BEGIN>&lt;</BEGIN>
    <END>&gt;</END>
    </SPAN>


  </RULES>
  <RULES SET="EXPRESSION"
      DEFAULT="KEYWORD2"
      HIGHLIGHT_DIGITS="TRUE"
      ESCAPE="\"
    >
    <SPAN TYPE="LITERAL1">
    <BEGIN>"</BEGIN>
    <END>"</END>
    </SPAN>
    <SPAN TYPE="OPERATOR" DELEGATE="EXPRESSION">
      <BEGIN>(</BEGIN><END>)</END>
    </SPAN>
    <!-- Builtins -->
    <MARK_FOLLOWING TYPE="FUNCTION">?</MARK_FOLLOWING>
    <KEYWORDS IGNORE_CASE="FALSE">
      <KEYWORD1>true</KEYWORD1>
      <KEYWORD1>false</KEYWORD1>
      <KEYWORD1>as</KEYWORD1>
      <KEYWORD1>in</KEYWORD1>
      <OPERATOR>!</OPERATOR>
      <OPERATOR>=</OPERATOR>
      <OPERATOR>!=</OPERATOR>
      <OPERATOR>==</OPERATOR>
      <OPERATOR>|</OPERATOR>
      <OPERATOR>||</OPERATOR>
      <OPERATOR>&amp;</OPERATOR>
      <OPERATOR>&amp;&amp;</OPERATOR>
      <OPERATOR>&lt;</OPERATOR>
      <OPERATOR>&gt;</OPERATOR>
      <OPERATOR>&lt;=</OPERATOR>
      <OPERATOR>&gt;=</OPERATOR>
      <OPERATOR>gt</OPERATOR>
      <OPERATOR>gte</OPERATOR>
      <OPERATOR>lt</OPERATOR>
      <OPERATOR>lte</OPERATOR>
      <OPERATOR>*</OPERATOR>
      <OPERATOR>/</OPERATOR>
      <OPERATOR>-</OPERATOR>
      <OPERATOR>+</OPERATOR>
      <OPERATOR>.</OPERATOR>
      <OPERATOR>:</OPERATOR>
      <OPERATOR>%</OPERATOR>
      <OPERATOR>[</OPERATOR>
      <OPERATOR>]</OPERATOR>
      <OPERATOR>{</OPERATOR>
      <OPERATOR>}</OPERATOR>
      <OPERATOR>;</OPERATOR>
    </KEYWORDS>
  </RULES>

  <RULES SET="TAGS" DEFAULT="MARKUP" ESCAPE="\">
    <SPAN TYPE="LITERAL1" DELEGATE="INQUOTE">
    <BEGIN>"</BEGIN>
    <END>"</END>
    </SPAN>

    <SPAN TYPE="LITERAL1" DELEGATE="INQUOTE">
    <BEGIN>'</BEGIN>
    <END>'</END>
    </SPAN>

    <SEQ TYPE="OPERATOR">=</SEQ>
  </RULES>

  
  <!-- a ruleset for when we are within a quoted string within an SGML tag
       It can contain FTL interpolations -->
  <RULES SET="INQUOTE">
    <SPAN TYPE="KEYWORD1" DELEGATE="EXPRESSION">
    <BEGIN>${</BEGIN>
    <END>}</END>
    </SPAN>
    <SPAN TYPE="KEYWORD1" DELEGATE="EXPRESSION">
    <BEGIN>#{</BEGIN>
    <END>}</END>
    </SPAN>
  </RULES>

  <!-- empty ruleset to delegate to for spots where any non-whitespace is invalid -->
  <RULES SET="INVALID" DEFAULT="INVALID" />
</MODE>
