=== albfan/jEdit/trunk/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | LITERAL1 | LITERAL2
	| LABEL | KEYWORD1 | KEYWORD2 | KEYWORD3 | FUNCTION
	| MARKUP | OPERATOR | DIGIT | INVALID )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-standard-mix 'TYPE %tokens; "NULL"
	AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( TERMINATE | SEQ | SEQ_REGEXP | SPAN | SPAN_REGEXP
	| EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-standard-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-standard-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-standard-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-standard-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ELEMENT END ( #PCDATA ) >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-standard-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-standard-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-standard-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-standard-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS ( NULL | COMMENT1 | COMMENT2 | LITERAL1 | LITERAL2
	| LABEL | KEYWORD1 | KEYWORD2 | KEYWORD3 | FUNCTION | MARKUP
	| OPERATOR | DIGIT | INVALID )+ >

<!-- KEYWORDS children -->
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== albfan/jEdit/trunk/modes/ml.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- SML MODE by Ingmar Stein -->
<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="(*"/>
		<PROPERTY NAME="commentEnd" VALUE="*)"/>
	</PROPS>

	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- comments -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>(*</BEGIN>
			<END>*)</END>
		</SPAN>

		<!-- character literals -->
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>#"</BEGIN>
			<END>"</END>
		</SPAN>

		<!-- string literals -->
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<!-- built-in operators -->

		<!-- infix precedence 7 -->
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>

		<!-- infix precedence 6 -->
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>

		<!-- infix precedence 5 -->
		<SEQ TYPE="OPERATOR">::</SEQ>
		<SEQ TYPE="OPERATOR">@</SEQ>

		<!-- infix precedence 4 -->
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>

		<!-- infix precedence 3 -->
		<SEQ TYPE="OPERATOR">:=</SEQ>

		<!-- reserved words -->
		<!-- <SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">{</SEQ>
		<SEQ TYPE="NULL">}</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">:&gt;</SEQ>
		<SEQ TYPE="NULL">:</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">...</SEQ>
		<SEQ TYPE="NULL">_</SEQ>
		<SEQ TYPE="NULL">|</SEQ>
		<SEQ TYPE="NULL">=&gt;</SEQ>
		<SEQ TYPE="NULL">-&gt;</SEQ>
		<SEQ TYPE="NULL">#</SEQ> -->

		<KEYWORDS>
			<!-- built-in operators -->

			<!-- infix precedence 7 -->
			<OPERATOR>div</OPERATOR>
			<OPERATOR>mod</OPERATOR>

			<!-- infix precedence 3 -->
			<OPERATOR>o</OPERATOR>

			<!-- infix precedence 0 -->
			<OPERATOR>before</OPERATOR>

			<!-- reserved words -->
			<KEYWORD1>abstype</KEYWORD1>
			<KEYWORD1>and</KEYWORD1>
			<KEYWORD1>andalso</KEYWORD1>
			<KEYWORD1>as</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>datatype</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>end</KEYWORD1>
			<KEYWORD1>eqtype</KEYWORD1>
			<KEYWORD1>exception</KEYWORD1>
			<KEYWORD1>fn</KEYWORD1>
			<KEYWORD1>fun</KEYWORD1>
			<KEYWORD1>functor</KEYWORD1>
			<KEYWORD1>handle</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>include</KEYWORD1>
			<KEYWORD1>infix</KEYWORD1>
			<KEYWORD1>infixr</KEYWORD1>
			<KEYWORD1>let</KEYWORD1>
			<KEYWORD1>local</KEYWORD1>
			<KEYWORD1>nonfix</KEYWORD1>
			<KEYWORD1>of</KEYWORD1>
			<KEYWORD1>op</KEYWORD1>
			<KEYWORD1>open</KEYWORD1>
			<KEYWORD1>orelse</KEYWORD1>
			<KEYWORD1>raise</KEYWORD1>
			<KEYWORD1>rec</KEYWORD1>
			<KEYWORD1>sharing</KEYWORD1>
			<KEYWORD1>sig</KEYWORD1>
			<KEYWORD1>signature</KEYWORD1>
			<KEYWORD1>struct</KEYWORD1>
			<KEYWORD1>structure</KEYWORD1>
			<KEYWORD1>then</KEYWORD1>
			<KEYWORD1>type</KEYWORD1>
			<KEYWORD1>val</KEYWORD1>
			<KEYWORD1>where</KEYWORD1>
			<KEYWORD1>with</KEYWORD1>
			<KEYWORD1>withtype</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>

			<!-- built-in types -->
			<KEYWORD3>array</KEYWORD3>
			<KEYWORD3>bool</KEYWORD3>
			<KEYWORD3>char</KEYWORD3>
			<KEYWORD3>exn</KEYWORD3>
			<KEYWORD3>frag</KEYWORD3>
			<KEYWORD3>int</KEYWORD3>
			<KEYWORD3>list</KEYWORD3>
			<KEYWORD3>option</KEYWORD3>
			<KEYWORD3>order</KEYWORD3>
			<KEYWORD3>real</KEYWORD3>
			<KEYWORD3>ref</KEYWORD3>
			<KEYWORD3>string</KEYWORD3>
			<KEYWORD3>substring</KEYWORD3>
			<KEYWORD3>unit</KEYWORD3>
			<KEYWORD3>vector</KEYWORD3>
			<KEYWORD3>word</KEYWORD3>
			<KEYWORD3>word8</KEYWORD3>

			<!-- build-in exception constructors -->
			<KEYWORD2>Bind</KEYWORD2>
			<KEYWORD2>Chr</KEYWORD2>
			<KEYWORD2>Domain</KEYWORD2>
			<KEYWORD2>Div</KEYWORD2>
			<KEYWORD2>Fail</KEYWORD2>
			<KEYWORD2>Graphic</KEYWORD2>
			<KEYWORD2>Interrupt</KEYWORD2>
			<KEYWORD2>Io</KEYWORD2>
			<KEYWORD2>Match</KEYWORD2>
			<KEYWORD2>Option</KEYWORD2>
			<KEYWORD2>Ord</KEYWORD2>
			<KEYWORD2>Overflow</KEYWORD2>
			<KEYWORD2>Size</KEYWORD2>
			<KEYWORD2>Subscript</KEYWORD2>
			<KEYWORD2>SysErr</KEYWORD2>

			<!-- built-in literals -->
			<LITERAL2>false</LITERAL2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>QUOTE</LITERAL2>
			<LITERAL2>ANTIQUOTE</LITERAL2>
			<LITERAL2>nil</LITERAL2>
			<LITERAL2>NONE</LITERAL2>
			<LITERAL2>SOME</LITERAL2>
			<LITERAL2>LESS</LITERAL2>
			<LITERAL2>EQUAL</LITERAL2>
			<LITERAL2>GREATER</LITERAL2>
		</KEYWORDS>
	</RULES>
</MODE>

=== albfan/jEdit/trunk/modes/javacc.xml
<?xml version="1.0"?>
<!DOCTYPE MODE SYSTEM "xmode.dtd">
<MODE>
    <RULES IGNORE_CASE="FALSE">
        <IMPORT DELEGATE="java::MAIN"/>
        <KEYWORDS>
            <KEYWORD1>EOF</KEYWORD1>
            <KEYWORD1>IGNORE_CASE</KEYWORD1>
            <KEYWORD1>JAVACODE</KEYWORD1>
            <KEYWORD1>LOOKAHEAD</KEYWORD1>
            <KEYWORD1>MORE</KEYWORD1>
            <KEYWORD1>PARSER_BEGIN</KEYWORD1>
            <KEYWORD1>PARSER_END</KEYWORD1>
            <KEYWORD1>SKIP</KEYWORD1>
            <KEYWORD1>SPECIAL_TOKEN</KEYWORD1>
            <KEYWORD1>TOKEN</KEYWORD1>
            <KEYWORD1>TOKEN_MGR_DECLS</KEYWORD1>
            <KEYWORD1>options</KEYWORD1>
        </KEYWORDS>
    </RULES>
</MODE>

=== albfan/jEdit/trunk/modes/cplusplus.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
    <PROPS>
        <PROPERTY NAME="commentStart" VALUE="/*" />
        <PROPERTY NAME="commentEnd" VALUE="*/" />
        <PROPERTY NAME="lineComment" VALUE="//" />
        <PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />

        <!-- Auto indent -->
        <PROPERTY NAME="indentOpenBrackets" VALUE="{" />
        <PROPERTY NAME="indentCloseBrackets" VALUE="}" />
        <PROPERTY NAME="indentNextLine"
            VALUE="\s*(((if|while)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
        <!-- set this to 'true' if you want to use GNU coding style -->
        <PROPERTY NAME="doubleBracketIndent" VALUE="false" />
        <PROPERTY NAME="lineUpClosingBracket" VALUE="true" />
    </PROPS>
    <RULES ESCAPE="\"
        IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE"
        DIGIT_RE="(0x[[:xdigit:]]+[lL]?|[[:digit:]]+(e[[:digit:]]*)?[lLdDfF]?)">

        <!-- Doxygen comment, Javadoc style -->
        <SPAN TYPE="COMMENT3" DELEGATE="doxygen::DOXYGEN">
            <BEGIN>/**</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- Doxygen comment, Qt style -->
        <SPAN TYPE="COMMENT3" DELEGATE="doxygen::DOXYGEN">
            <BEGIN>/*!</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- C style comment -->
        <SPAN TYPE="COMMENT1">
            <BEGIN>/*</BEGIN>
            <END>*/</END>
        </SPAN>

        <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
            <BEGIN>"</BEGIN>
            <END>"</END>
        </SPAN>
        <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
            <BEGIN>'</BEGIN>
            <END>'</END>
        </SPAN>

        <!-- preprocessor statements -->
        <SEQ TYPE="KEYWORD2">##</SEQ>
        <EOL_SPAN TYPE="KEYWORD2" DELEGATE="c::CPP">#</EOL_SPAN>

        <EOL_SPAN TYPE="COMMENT2">//</EOL_SPAN>
        <SEQ TYPE="OPERATOR">=</SEQ>
        <SEQ TYPE="OPERATOR">!</SEQ>
        <SEQ TYPE="OPERATOR">&gt;=</SEQ>
        <SEQ TYPE="OPERATOR">&lt;=</SEQ>
        <SEQ TYPE="OPERATOR">+</SEQ>
        <SEQ TYPE="OPERATOR">-</SEQ>
        <SEQ TYPE="OPERATOR">/</SEQ>

        <SEQ TYPE="OPERATOR">*</SEQ>
        <SEQ TYPE="OPERATOR">&gt;</SEQ>
        <SEQ TYPE="OPERATOR">&lt;</SEQ>
        <SEQ TYPE="OPERATOR">%</SEQ>
        <SEQ TYPE="OPERATOR">&amp;</SEQ>
        <SEQ TYPE="OPERATOR">|</SEQ>
        <SEQ TYPE="OPERATOR">^</SEQ>
        <SEQ TYPE="OPERATOR">~</SEQ>
        <SEQ TYPE="OPERATOR">}</SEQ>
        <SEQ TYPE="OPERATOR">{</SEQ>
        
        <MARK_PREVIOUS TYPE="FUNCTION">::</MARK_PREVIOUS>
        
        <MARK_PREVIOUS AT_WHITESPACE_END="TRUE"
            EXCLUDE_MATCH="TRUE"
            TYPE="LABEL">:</MARK_PREVIOUS>

        <!-- Function calls -->
        <MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

        <KEYWORDS>
            <KEYWORD3>and</KEYWORD3>
            <KEYWORD3>and_eq</KEYWORD3>
            <KEYWORD2>asm</KEYWORD2>
            <KEYWORD1>auto</KEYWORD1>
            <KEYWORD3>bitand</KEYWORD3>
            <KEYWORD3>bitor</KEYWORD3>
            <KEYWORD3>bool</KEYWORD3>
            <KEYWORD1>break</KEYWORD1>
            <KEYWORD1>case</KEYWORD1>
            <KEYWORD1>catch</KEYWORD1>
            <KEYWORD3>char</KEYWORD3>
            <KEYWORD3>class</KEYWORD3>
            <KEYWORD3>compl</KEYWORD3>
            <KEYWORD1>const</KEYWORD1>
            <KEYWORD3>const_cast</KEYWORD3>
            <KEYWORD1>continue</KEYWORD1>
            <KEYWORD1>default</KEYWORD1>
            <KEYWORD1>delete</KEYWORD1>
            <KEYWORD1>do</KEYWORD1>
            <KEYWORD3>double</KEYWORD3>
            <KEYWORD3>dynamic_cast</KEYWORD3>
            <KEYWORD1>else</KEYWORD1>
            <KEYWORD3>enum</KEYWORD3>
            <KEYWORD1>explicit</KEYWORD1>
            <KEYWORD2>export</KEYWORD2>
            <KEYWORD2>extern</KEYWORD2>
            <LITERAL2>false</LITERAL2>
            <KEYWORD3>float</KEYWORD3>
            <KEYWORD1>for</KEYWORD1>
            <KEYWORD1>friend</KEYWORD1>
            <KEYWORD1>goto</KEYWORD1>
            <KEYWORD1>if</KEYWORD1>
            <KEYWORD1>inline</KEYWORD1>
            <KEYWORD3>int</KEYWORD3>
            <KEYWORD3>long</KEYWORD3>
            <KEYWORD3>mutable</KEYWORD3>
            <KEYWORD2>namespace</KEYWORD2>
            <KEYWORD1>new</KEYWORD1>
            <KEYWORD3>not</KEYWORD3>
            <KEYWORD3>not_eq</KEYWORD3>
            <KEYWORD3>operator</KEYWORD3>
            <KEYWORD3>or</KEYWORD3>
            <KEYWORD3>or_eq</KEYWORD3>
            <KEYWORD1>private</KEYWORD1>
            <KEYWORD1>protected</KEYWORD1>
            <KEYWORD1>public</KEYWORD1>
            <KEYWORD1>register</KEYWORD1>
            <KEYWORD3>reinterpret_cast</KEYWORD3>
            <KEYWORD1>return</KEYWORD1>
            <KEYWORD3>short</KEYWORD3>
            <KEYWORD3>signed</KEYWORD3>
            <KEYWORD1>sizeof</KEYWORD1>
            <KEYWORD1>static</KEYWORD1>
            <KEYWORD3>static_cast</KEYWORD3>
            <KEYWORD3>struct</KEYWORD3>
            <KEYWORD1>switch</KEYWORD1>
            <KEYWORD3>template</KEYWORD3>
            <LITERAL2>this</LITERAL2>
            <KEYWORD1>throw</KEYWORD1>
            <LITERAL2>true</LITERAL2>
            <KEYWORD1>try</KEYWORD1>
            <KEYWORD3>typedef</KEYWORD3>
            <KEYWORD3>typeid</KEYWORD3>
            <KEYWORD3>typename</KEYWORD3>
            <KEYWORD3>union</KEYWORD3>
            <KEYWORD3>unsigned</KEYWORD3>
            <KEYWORD2>using</KEYWORD2>
            <KEYWORD1>virtual</KEYWORD1>
            <KEYWORD1>void</KEYWORD1>
            <KEYWORD1>volatile</KEYWORD1>
            <KEYWORD3>wchar_t</KEYWORD3>
            <KEYWORD1>while</KEYWORD1>
            <KEYWORD3>xor</KEYWORD3>
            <KEYWORD3>xor_eq</KEYWORD3>
            <LITERAL2>NULL</LITERAL2>
        </KEYWORDS>
    </RULES>
</MODE>

=== albfan/jEdit/trunk/modes/xq.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;!--" />
		<PROPERTY NAME="commentEnd" VALUE="--&gt;" />
		<PROPERTY NAME="commentStart" VALUE="(:" />
		<PROPERTY NAME="commentEnd" VALUE=":)" />
		<PROPERTY NAME="wordBreakChars" VALUE=":,+=&lt;&gt;/?^&amp;*" />

		<!-- Auto indent -->
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<PROPERTY NAME="indentNextLine"
			VALUE="\s*(((if)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="lineUpClosingBracket" VALUE="true" />
	</PROPS>
	<RULES>
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>
		
		
		<!-- DTD Entity declarations -->
		<SPAN TYPE="KEYWORD2" DELEGATE="ENTITY-TAGS">
			<BEGIN>&lt;!ENTITY</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- CDATA sections -->
		<SPAN TYPE="KEYWORD2" DELEGATE="CDATA">
			<BEGIN>&lt;![CDATA[</BEGIN>
			<END>]]&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- PI directives -->
		<SPAN TYPE="KEYWORD3">
			<BEGIN>&lt;?</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
	</RULES>
	
	<RULES SET="TAGS" DEFAULT="MARKUP" NO_WORD_SEP="-_">
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>
		

		<SEQ TYPE="MARKUP">/</SEQ>
		<MARK_PREVIOUS TYPE="LABEL" EXCLUDE_MATCH="TRUE">:</MARK_PREVIOUS>
<!-- 		<SEQ TYPE="OPERATOR">:</SEQ>
 --> 		</RULES>
	
	<RULES SET="DTD-TAGS" DEFAULT="KEYWORD2" IGNORE_CASE="FALSE">
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>--</BEGIN>
			<END>--</END>
		</SPAN>

		<!-- Parameter entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>%</BEGIN>
			<END>;</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<!-- This appears in some SGML documents -->
		<SPAN TYPE="KEYWORD2" DELEGATE="MAIN">
			<BEGIN>[</BEGIN>
			<END>]</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">(</SEQ>
		<SEQ TYPE="OPERATOR">)</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">?</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">,</SEQ>

		<KEYWORDS>
			<KEYWORD1>CDATA</KEYWORD1>
			<KEYWORD1>EMPTY</KEYWORD1>
			<KEYWORD1>INCLUDE</KEYWORD1>
			<KEYWORD1>IGNORE</KEYWORD1>
			<KEYWORD1>NDATA</KEYWORD1>
			<KEYWORD1>#IMPLIED</KEYWORD1>
			<KEYWORD1>#PCDATA</KEYWORD1>
			<KEYWORD1>#REQUIRED</KEYWORD1>
		</KEYWORDS>
	</RULES>
	
	<RULES SET="ENTITY-TAGS" DEFAULT="KEYWORD2">
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>--</BEGIN>
			<END>--</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>

		<SEQ TYPE="OPERATOR">%</SEQ>

		<KEYWORDS>
			<KEYWORD1>SYSTEM</KEYWORD1>
		</KEYWORDS>
	</RULES>
	
	<RULES SET="CDATA" DEFAULT="COMMENT2">
		<!-- no rules -->
	</RULES>

	<RULES ESCAPE="\"
		IGNORE_CASE="FALSE"
		HIGHLIGHT_DIGITS="TRUE"
		DIGIT_RE="(0x[[:xdigit:]]+[lL]?|[[:digit:]]+(e[[:digit:]]*)?[lLdDfF]?)">

		<!-- XQuery style comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>(:</BEGIN>
			<END>:)</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>
		
		<MARK_FOLLOWING TYPE="KEYWORD2">$</MARK_FOLLOWING>

		

		<!-- Function calls -->
		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>
	
		<SEQ TYPE="OPERATOR">,</SEQ>
		
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!=</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		
		<SEQ TYPE="OPERATOR">&lt;&lt;</SEQ>
		<SEQ TYPE="OPERATOR">&gt;&gt;</SEQ>
		
		<SEQ TYPE="OPERATOR">+</SEQ>
<!-- 
		<SEQ TYPE="OPERATOR">-</SEQ>
 -->
 		<SEQ TYPE="OPERATOR">*</SEQ>
		
		<!-- unary -/+ ? -->
		
		<SEQ TYPE="OPERATOR">|</SEQ>
		
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">//</SEQ>
		
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		
		<KEYWORDS>
			<OPERATOR>some</OPERATOR>
			<OPERATOR>every</OPERATOR>
			<OPERATOR>or</OPERATOR>
			
			<OPERATOR>and</OPERATOR>
			
			<OPERATOR>instance of</OPERATOR>
			
			<OPERATOR>treat as</OPERATOR>
			
			<OPERATOR>castable as</OPERATOR>
			
			<OPERATOR>cast as</OPERATOR>
			
			<OPERATOR>eq</OPERATOR>
			<OPERATOR>ne</OPERATOR>
			<OPERATOR>lt</OPERATOR>
			<OPERATOR>gt</OPERATOR>
			<OPERATOR>ge</OPERATOR>
			<OPERATOR>is</OPERATOR>
			
			<OPERATOR>to</OPERATOR>
			
			<OPERATOR>div</OPERATOR>
			<OPERATOR>idiv</OPERATOR>
			<OPERATOR>mod</OPERATOR>
			
			<OPERATOR>union</OPERATOR>
			
			<OPERATOR>intersect</OPERATOR>
			<OPERATOR>except</OPERATOR>
			
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>to</KEYWORD1>
			<KEYWORD1>at</KEYWORD1>
			
			<KEYWORD1>let</KEYWORD1>
			<KEYWORD1>:=</KEYWORD1>
			
			<KEYWORD1>where</KEYWORD1>
			
			<KEYWORD1>stable</KEYWORD1>
			<KEYWORD1>order</KEYWORD1>
			<KEYWORD1>by</KEYWORD1>
			
			<LITERAL2>ascending</LITERAL2>
			<LITERAL2>descending</LITERAL2>
			
			<LITERAL2>greatest</LITERAL2>
			<LITERAL2>least</LITERAL2>
			<LITERAL2>collation</LITERAL2>
			
			<KEYWORD3>typeswitch</KEYWORD3>
			<KEYWORD3>default</KEYWORD3>
			
			<KEYWORD1>cast</KEYWORD1>
			<KEYWORD1>as</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>then</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			
			<LITERAL2>true</LITERAL2>
			<LITERAL2>false</LITERAL2>
			
			<KEYWORD3>xquery</KEYWORD3>
			<KEYWORD3>version</KEYWORD3>

			<KEYWORD3>declare</KEYWORD3>
			<KEYWORD3>function</KEYWORD3>
			<KEYWORD3>library</KEYWORD3>
			<KEYWORD3>variable</KEYWORD3>
			<KEYWORD3>module</KEYWORD3>
			<KEYWORD3>namespace</KEYWORD3>
			<KEYWORD3>local</KEYWORD3>

			<KEYWORD3>validate</KEYWORD3>
			<KEYWORD3>import</KEYWORD3>
			<KEYWORD3>schema</KEYWORD3>
			<KEYWORD3>validation</KEYWORD3>
			<KEYWORD3>collection</KEYWORD3>

			<KEYWORD3>ancestor</KEYWORD3>
			<KEYWORD3>descendant</KEYWORD3>
			<KEYWORD3>self</KEYWORD3>
			<KEYWORD3>parent</KEYWORD3>
			<KEYWORD3>child</KEYWORD3>
			<KEYWORD3>self</KEYWORD3>
			<KEYWORD3>descendant-or-self</KEYWORD3>
			<KEYWORD3>ancestor-or-self</KEYWORD3>
			<KEYWORD3>preceding-sibling</KEYWORD3>
			<KEYWORD3>following-sibling</KEYWORD3>
			<KEYWORD3>following</KEYWORD3>
			<KEYWORD3>preceding</KEYWORD3>
			
			<KEYWORD4>xs:integer</KEYWORD4>
			<KEYWORD4>xs:decimal</KEYWORD4>
			<KEYWORD4>xs:double</KEYWORD4>
			<KEYWORD4>xs:string</KEYWORD4>
			<KEYWORD4>xs:date</KEYWORD4>
			<KEYWORD4>xs:time</KEYWORD4>
			<KEYWORD4>xs:dateTime</KEYWORD4>
			<KEYWORD4>xs:boolean</KEYWORD4>

			<KEYWORD4>item</KEYWORD4>
			<KEYWORD4>element</KEYWORD4>
			<KEYWORD4>attribute</KEYWORD4>
			<KEYWORD4>comment</KEYWORD4>
			<KEYWORD4>document</KEYWORD4>
			<KEYWORD4>document-node</KEYWORD4>
			<KEYWORD4>node</KEYWORD4>
			<KEYWORD4>empty</KEYWORD4>

			<FUNCTION></FUNCTION>
		</KEYWORDS>
	</RULES>
	
</MODE>
