=== albfan/jEdit/tags/jedit-4-2-pre3/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | COMMENT3 | COMMENT4 |
	DIGIT | FUNCTION | INVALID | KEYWORD1 | KEYWORD2 | KEYWORD3 | KEYWORD4 |
	LABEL | LITERAL1 | LITERAL2 | LITERAL3 | LITERAL4 | MARKUP | OPERATOR )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-type 'TYPE %tokens; "NULL"' >
<!ENTITY % att-position-mix 'AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"
	NO_ESCAPE %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( IMPORT | TERMINATE | SEQ | SEQ_REGEXP | SPAN
	| SPAN_REGEXP | EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- IMPORT element -->
<!ELEMENT IMPORT EMPTY >
<!ATTLIST IMPORT DELEGATE CDATA #REQUIRED >

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ATTLIST BEGIN %att-position-mix; >
<!ELEMENT END ( #PCDATA ) >
<!ATTLIST END %att-position-mix; >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS (%tokens;)+ >

<!-- KEYWORDS children -->
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT COMMENT3 ( #PCDATA ) >
<!ELEMENT COMMENT4 ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT KEYWORD4 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LITERAL3 ( #PCDATA ) >
<!ELEMENT LITERAL4 ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== albfan/jEdit/tags/jedit-4-0-pre8/modes/batch.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- 	
	Compiled by Mirco Bova on 04-12-2001 
	this file is based on the original JEdit batch.xml mode.
	The main upgrade consisting in adding the standard MS-DOS
	commands as keywords and functions:
	- keywords =		internal shell commands;
	-	functions =		standard MS-DOS commands (.exe or .com in DOS or
									windows\command directory).
-->

<!-- The keywords and functions here defined are those of MS-DOS 6.22 -->

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="rem " />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="TRUE" HIGHLIGHT_DIGITS="FALSE">
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- 'echo off' statements -->
		<SEQ TYPE="KEYWORD3">@</SEQ>

		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>

		<SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">=</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>

		<!-- labels - eg :test -->
		<EOL_SPAN TYPE="LABEL" AT_LINE_START="TRUE">:</EOL_SPAN>

		<!-- comments -->
		<EOL_SPAN TYPE="COMMENT1">REM</EOL_SPAN>

		<!-- literals -->
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		
		<!-- variables -->
		<SEQ TYPE="KEYWORD2">%1</SEQ>
		<SEQ TYPE="KEYWORD2">%2</SEQ>
		<SEQ TYPE="KEYWORD2">%3</SEQ>
		<SEQ TYPE="KEYWORD2">%4</SEQ>
		<SEQ TYPE="KEYWORD2">%5</SEQ>
		<SEQ TYPE="KEYWORD2">%6</SEQ>
		<SEQ TYPE="KEYWORD2">%7</SEQ>
		<SEQ TYPE="KEYWORD2">%8</SEQ>
		<SEQ TYPE="KEYWORD2">%9</SEQ>
		<SPAN TYPE="KEYWORD2" NO_LINE_BREAK="TRUE">
			<BEGIN>%</BEGIN>
			<END>%</END>
		</SPAN>

		<KEYWORDS IGNORE_CASE="TRUE">
			<!-- KEYWORD1 are internal MS-DOS shell commands -->
			<KEYWORD1>cd</KEYWORD1>
			<KEYWORD1>chdir</KEYWORD1>
			<KEYWORD1>md</KEYWORD1>
			<KEYWORD1>mkdir</KEYWORD1>
		
			<KEYWORD1>cls</KEYWORD1>
		
			<KEYWORD1>if</KEYWORD1>
		
			<KEYWORD1>echo</KEYWORD1>
			<KEYWORD1>echo.</KEYWORD1>
		
			<KEYWORD1>move</KEYWORD1>
			<KEYWORD1>copy</KEYWORD1>
			<KEYWORD1>move</KEYWORD1>
			<KEYWORD1>ren</KEYWORD1>
			<KEYWORD1>del</KEYWORD1>
			<KEYWORD1>set</KEYWORD1>
		
			<!-- KEYWORD2 are commands options -->
		
			<KEYWORD2>exist</KEYWORD2>
			<KEYWORD2>errorlevel</KEYWORD2>
			<KEYWORD1>not</KEYWORD1>
		
			<!-- goto is a special case we want to distinguish it -->
			<KEYWORD3>goto</KEYWORD3>

			<!-- FUNCTION are standard MS-DOS commands -->
			<!-- (those you find as stand-alone .exe or .com) in win95 %windows_root%\command folder -->
			<FUNCTION>APPEND</FUNCTION>
			<FUNCTION>ATTRIB</FUNCTION>
			<FUNCTION>CHKDSK</FUNCTION>
			<FUNCTION>CHOICE</FUNCTION>
			<FUNCTION>DEBUG</FUNCTION>
			<FUNCTION>DEFRAG</FUNCTION>
			<FUNCTION>DELTREE</FUNCTION>
			<FUNCTION>DISKCOMP</FUNCTION>
			<FUNCTION>DISKCOPY</FUNCTION>
			<FUNCTION>DOSKEY</FUNCTION>
			<FUNCTION>DRVSPACE</FUNCTION>
			<FUNCTION>EMM386</FUNCTION>
			<FUNCTION>EXPAND</FUNCTION>
			<FUNCTION>FASTOPEN</FUNCTION>
			<FUNCTION>FC</FUNCTION>
			<FUNCTION>FDISK</FUNCTION>
			<FUNCTION>FIND</FUNCTION>
			<FUNCTION>FORMAT</FUNCTION>
			<FUNCTION>GRAPHICS</FUNCTION>
			<FUNCTION>KEYB</FUNCTION>
			<FUNCTION>LABEL</FUNCTION>
			<FUNCTION>LOADFIX</FUNCTION>
			<FUNCTION>MEM</FUNCTION>
			<FUNCTION>MODE</FUNCTION>
			<FUNCTION>MORE</FUNCTION>
			<FUNCTION>MOVE</FUNCTION>
			<FUNCTION>MSCDEX</FUNCTION>
			<FUNCTION>NLSFUNC</FUNCTION>
			<FUNCTION>POWER</FUNCTION>
			<FUNCTION>PRINT</FUNCTION>
			<FUNCTION>REPLACE</FUNCTION>
			<FUNCTION>RESTORE</FUNCTION>
			<FUNCTION>SETVER</FUNCTION>
			<FUNCTION>SHARE</FUNCTION>
			<FUNCTION>SORT</FUNCTION>
			<FUNCTION>SUBST</FUNCTION>
			<FUNCTION>SYS</FUNCTION>
			<FUNCTION>TREE</FUNCTION>
			<FUNCTION>UNDELETE</FUNCTION>
			<FUNCTION>UNFORMAT</FUNCTION>
			<FUNCTION>VSAFE</FUNCTION>
			<FUNCTION>XCOPY</FUNCTION>
		</KEYWORDS>
	</RULES>
</MODE>
