=== albfan/jEdit/tags/jedit-4-2-pre3/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | COMMENT3 | COMMENT4 |
	DIGIT | FUNCTION | INVALID | KEYWORD1 | KEYWORD2 | KEYWORD3 | KEYWORD4 |
	LABEL | LITERAL1 | LITERAL2 | LITERAL3 | LITERAL4 | MARKUP | OPERATOR )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-type 'TYPE %tokens; "NULL"' >
<!ENTITY % att-position-mix 'AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"
	NO_ESCAPE %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( IMPORT | TERMINATE | SEQ | SEQ_REGEXP | SPAN
	| SPAN_REGEXP | EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- IMPORT element -->
<!ELEMENT IMPORT EMPTY >
<!ATTLIST IMPORT DELEGATE CDATA #REQUIRED >

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ATTLIST BEGIN %att-position-mix; >
<!ELEMENT END ( #PCDATA ) >
<!ATTLIST END %att-position-mix; >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS (%tokens;)+ >

<!-- KEYWORDS children -->
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT COMMENT3 ( #PCDATA ) >
<!ELEMENT COMMENT4 ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT KEYWORD4 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LITERAL3 ( #PCDATA ) >
<!ELEMENT LITERAL4 ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== albfan/jEdit/tags/jedit-4-2-pre6/modes/velocity.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="#*" />
		<PROPERTY NAME="commentEnd" VALUE="*#" />
		<PROPERTY NAME="lineComment" VALUE="##" />
	</PROPS>
	<RULES IGNORE_CASE="TRUE">
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- JavaScript -->
		<SPAN TYPE="MARKUP" DELEGATE="JAVASCRIPT">
			<BEGIN>&lt;SCRIPT</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<!-- stylesheet -->
		<SPAN TYPE="MARKUP" DELEGATE="CSS">
			<BEGIN>&lt;STYLE</BEGIN>
			<END>&lt;/STYLE&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="html::TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
		<IMPORT DELEGATE="VELOCITY" />
	</RULES>

	<RULES SET="VELOCITY">
		<SPAN TYPE="COMMENT2">
			<BEGIN>#*</BEGIN>
			<END>*#</END>
		</SPAN>

		<EOL_SPAN TYPE="COMMENT3">##</EOL_SPAN>

		<SPAN TYPE="KEYWORD3" NO_LINE_BREAK="TRUE">
			<BEGIN>${</BEGIN>
			<END>}</END>
		</SPAN>

		<MARK_FOLLOWING TYPE="KEYWORD3">$!</MARK_FOLLOWING>
		<MARK_FOLLOWING TYPE="KEYWORD3">$</MARK_FOLLOWING>

		<KEYWORDS>
			<KEYWORD1>#set</KEYWORD1>
			<KEYWORD1>#foreach</KEYWORD1>
			<KEYWORD1>#end</KEYWORD1>
			<KEYWORD1>#if</KEYWORD1>
			<KEYWORD1>#else</KEYWORD1>
			<KEYWORD1>#elseif</KEYWORD1>
			<KEYWORD1>#parse</KEYWORD1>
			<KEYWORD1>#macro</KEYWORD1>
			<KEYWORD1>#stop</KEYWORD1>
			<KEYWORD1>#include</KEYWORD1>
		</KEYWORDS>
	</RULES>

	<RULES SET="JAVASCRIPT" DEFAULT="MARKUP" IGNORE_CASE="TRUE">
		<SEQ TYPE="MARKUP" DELEGATE="JAVASCRIPT2">&gt;</SEQ>
		<!-- handle <SCRIPT SRC="..."> properly -->
		<SEQ TYPE="MARKUP" DELEGATE="BACK_TO_HTML">SRC=</SEQ>
	</RULES>

	<RULES SET="JAVASCRIPT2"
		ESCAPE="\"
		IGNORE_CASE="FALSE"
		HIGHLIGHT_DIGITS="TRUE"
		DIGIT_RE="(0x[[:xdigit:]]+[lL]?|[[:digit:]]+(e[[:digit:]]*)?[lLdDfF]?)">

		<IMPORT DELEGATE="VELOCITY" />
		<IMPORT DELEGATE="javascript::MAIN" />
	</RULES>

	<RULES SET="BACK_TO_HTML" DEFAULT="MARKUP">
		<SEQ TYPE="MARKUP" DELEGATE="MAIN">&gt;</SEQ>
	</RULES>

	<RULES SET="CSS" DEFAULT="MARKUP">
		<SEQ TYPE="MARKUP" DELEGATE="CSS2">&gt;</SEQ>
	</RULES>

	<RULES SET="CSS2"
		IGNORE_CASE="TRUE"
		HIGHLIGHT_DIGITS="TRUE"
		DIGIT_RE="[[:digit:]]+(pt|pc|in|mm|cm|em|ex|px|ms|s|%)"
		NO_WORD_SEP="-_">

		<IMPORT DELEGATE="VELOCITY" />
		<IMPORT DELEGATE="css::MAIN" />
	</RULES>
</MODE>

=== albfan/jEdit/tags/before-selection-manager/modes/objective-c.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
    <PROPS>
        <PROPERTY NAME="commentStart" VALUE="/*" />
        <PROPERTY NAME="commentEnd" VALUE="*/" />
        <PROPERTY NAME="lineComment" VALUE="//" />
        <PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />

        <!-- Auto indent -->
        <PROPERTY NAME="indentOpenBrackets" VALUE="{" />
        <PROPERTY NAME="indentCloseBrackets" VALUE="}" />
        <PROPERTY NAME="indentNextLine"
            VALUE="\s*(((if|while)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
        <!-- set this to 'true' if you want to use GNU coding style -->
        <PROPERTY NAME="doubleBracketIndent" VALUE="false" />
        <PROPERTY NAME="lineUpClosingBracket" VALUE="true" />
    </PROPS>
    <RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
        <!-- Doxygen comment, Javadoc style -->
        <SPAN TYPE="COMMENT3" DELEGATE="doxygen::DOXYGEN">
            <BEGIN>/**</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- Doxygen comment, Qt style -->
        <SPAN TYPE="COMMENT3" DELEGATE="doxygen::DOXYGEN">
            <BEGIN>/*!</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- C style comment -->
        <SPAN TYPE="COMMENT1">
            <BEGIN>/*</BEGIN>
            <END>*/</END>
        </SPAN>

        <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
            <BEGIN>"</BEGIN>
            <END>"</END>
        </SPAN>
        <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
            <BEGIN>'</BEGIN>
            <END>'</END>
        </SPAN>
        <SPAN TYPE="LITERAL3" NO_LINE_BREAK="TRUE">
            <BEGIN>@"</BEGIN>
            <END>"</END>
        </SPAN>

        <!-- preprocessor statements -->
        <SEQ TYPE="KEYWORD2">##</SEQ>
        <EOL_SPAN TYPE="KEYWORD2" DELEGATE="c::CPP">#</EOL_SPAN>
        
        <EOL_SPAN TYPE="COMMENT2">//</EOL_SPAN>
        <SEQ TYPE="OPERATOR">=</SEQ>
        <SEQ TYPE="OPERATOR">!</SEQ>
        <SEQ TYPE="OPERATOR">&gt;=</SEQ>
        <SEQ TYPE="OPERATOR">&lt;=</SEQ>
        <SEQ TYPE="OPERATOR">+</SEQ>
        <SEQ TYPE="OPERATOR">-</SEQ>
        <SEQ TYPE="OPERATOR">/</SEQ>

        <SEQ TYPE="OPERATOR">*</SEQ>
        <SEQ TYPE="OPERATOR">&gt;</SEQ>
        <SEQ TYPE="OPERATOR">&lt;</SEQ>
        <SEQ TYPE="OPERATOR">%</SEQ>
        <SEQ TYPE="OPERATOR">&amp;</SEQ>
        <SEQ TYPE="OPERATOR">|</SEQ>
        <SEQ TYPE="OPERATOR">^</SEQ>
        <SEQ TYPE="OPERATOR">~</SEQ>
        <SEQ TYPE="OPERATOR">}</SEQ>
        <SEQ TYPE="OPERATOR">{</SEQ>
        <MARK_PREVIOUS AT_WHITESPACE_END="TRUE"
            EXCLUDE_MATCH="TRUE"
            TYPE="LABEL">:</MARK_PREVIOUS>

        <!-- Function calls -->
        <MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

        <KEYWORDS>
            <!-- Types (Standard C) -->
            <KEYWORD3>char</KEYWORD3>
            <KEYWORD3>const</KEYWORD3>
            <KEYWORD3>double</KEYWORD3>
            <KEYWORD3>enum</KEYWORD3>
            <KEYWORD3>float</KEYWORD3>
            <KEYWORD3>int</KEYWORD3>
            <KEYWORD3>long</KEYWORD3>
            <KEYWORD3>short</KEYWORD3>
            <KEYWORD3>signed</KEYWORD3>
            <KEYWORD3>struct</KEYWORD3>
            <KEYWORD3>typedef</KEYWORD3>
            <KEYWORD3>union</KEYWORD3>
            <KEYWORD3>unsigned</KEYWORD3>
            <KEYWORD3>void</KEYWORD3>
            <!-- Types (Objective C) -->
            <KEYWORD3>id</KEYWORD3>
            <KEYWORD3>Class</KEYWORD3>
            <KEYWORD3>SEL</KEYWORD3>
            <KEYWORD3>IMP</KEYWORD3>
            <KEYWORD3>BOOL</KEYWORD3>
            
            <!-- Keywords (Standard C) -->
            <KEYWORD1>auto</KEYWORD1>
            <KEYWORD1>break</KEYWORD1>
            <KEYWORD1>case</KEYWORD1>
            <KEYWORD1>continue</KEYWORD1>
            <KEYWORD1>default</KEYWORD1>
            <KEYWORD1>do</KEYWORD1>
            <KEYWORD1>else</KEYWORD1>
            <KEYWORD1>extern</KEYWORD1>
            <KEYWORD1>for</KEYWORD1>
            <KEYWORD1>goto</KEYWORD1>
            <KEYWORD1>if</KEYWORD1>
            <KEYWORD1>register</KEYWORD1>
            <KEYWORD1>return</KEYWORD1>
            <KEYWORD1>sizeof</KEYWORD1>
            <KEYWORD1>static</KEYWORD1>
            <KEYWORD1>switch</KEYWORD1>
            <KEYWORD1>volatile</KEYWORD1>
            <KEYWORD1>while</KEYWORD1>
            <!-- Non-standard -->
            <KEYWORD1>asm</KEYWORD1>
            <KEYWORD1>inline</KEYWORD1>
            <!-- Keywords (Objective C) -->
            <KEYWORD1>oneway</KEYWORD1>
            <KEYWORD1>in</KEYWORD1>
            <KEYWORD1>out</KEYWORD1>
            <KEYWORD1>inout</KEYWORD1>
            <KEYWORD1>bycopy</KEYWORD1>
            <KEYWORD1>byref</KEYWORD1>
            <KEYWORD1>self</KEYWORD1>
            <KEYWORD1>super</KEYWORD1>
            
            <!-- Preprocessor Directives (Objective C)-->
            <KEYWORD1>@interface</KEYWORD1>
            <KEYWORD1>@implementation</KEYWORD1>
            <KEYWORD1>@protocol</KEYWORD1>
            <KEYWORD1>@end</KEYWORD1>
            <KEYWORD1>@private</KEYWORD1>
            <KEYWORD1>@protected</KEYWORD1>
            <KEYWORD1>@public</KEYWORD1>
            <KEYWORD1>@class</KEYWORD1>
            <KEYWORD1>@selector</KEYWORD1>
            <KEYWORD1>@endcode</KEYWORD1>
            <KEYWORD1>@defs</KEYWORD1>
            
            <LITERAL2>true</LITERAL2>
            <LITERAL2>false</LITERAL2>
            <LITERAL2>TRUE</LITERAL2>
            <LITERAL2>FALSE</LITERAL2>
            <LITERAL2>YES</LITERAL2>
            <LITERAL2>NO</LITERAL2>
            <LITERAL2>NULL</LITERAL2>
            <LITERAL2>nil</LITERAL2>
            <LITERAL2>NIl</LITERAL2>
        </KEYWORDS>
    </RULES>
</MODE>

=== albfan/jEdit/tags/jedit-4-2-pre10/modes/swig.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="/*" />
		<PROPERTY NAME="commentEnd" VALUE="*/" />
		<PROPERTY NAME="lineComment" VALUE="//" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />

		<!-- Auto indent -->
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<PROPERTY NAME="indentNextLine"
			VALUE="\s*(((if|while)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="lineUpClosingBracket" VALUE="true" />
	</PROPS>
	<RULES ESCAPE="\"
		IGNORE_CASE="FALSE"
		HIGHLIGHT_DIGITS="TRUE"
		DIGIT_RE="(0x[[:xdigit:]]+[lL]?|[[:digit:]]+(e[[:digit:]]*)?[lLdDfF]?)">

		<SPAN TYPE="LITERAL3">
			<BEGIN>%{</BEGIN>
			<END>%}</END>
		</SPAN>

		<!-- swig directive -->
		<MARK_FOLLOWING AT_WORD_START="TRUE" TYPE="KEYWORD4">%</MARK_FOLLOWING>

		<IMPORT DELEGATE="c::MAIN"/>
    </RULES>
</MODE>

=== albfan/jEdit/tags/before-selection-manager/modes/html.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;!--" />
		<PROPERTY NAME="commentEnd" VALUE="--&gt;" />
	</PROPS>
	<RULES IGNORE_CASE="TRUE">
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- JavaScript -->
		<SPAN TYPE="MARKUP" DELEGATE="JAVASCRIPT">
			<BEGIN>&lt;SCRIPT</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<!-- stylesheet -->
		<SPAN TYPE="MARKUP" DELEGATE="CSS">
			<BEGIN>&lt;STYLE</BEGIN>
			<END>&lt;/STYLE&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
	</RULES>

	<!-- ESCAPE is not exactly right but it is needed to correctly
	     handle JavaScript in on* parameters -->
	<RULES SET="TAGS" DEFAULT="MARKUP" ESCAPE="\">
		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>
	</RULES>

	<RULES SET="JAVASCRIPT" DEFAULT="MARKUP" IGNORE_CASE="TRUE">
		<SEQ TYPE="MARKUP" DELEGATE="javascript::MAIN">&gt;</SEQ>
		<!-- handle <SCRIPT SRC="..."> properly -->
		<SEQ TYPE="MARKUP" DELEGATE="BACK_TO_HTML">SRC=</SEQ>
	</RULES>

	<RULES SET="BACK_TO_HTML" DEFAULT="MARKUP">
		<SEQ TYPE="MARKUP" DELEGATE="html::MAIN">&gt;</SEQ>
	</RULES>

	<RULES SET="CSS" DEFAULT="MARKUP">
		<SEQ TYPE="MARKUP" DELEGATE="css::MAIN">&gt;</SEQ>
	</RULES>
</MODE>

=== albfan/jEdit/tags/jedit-4-0-pre5/modes/bibtex.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- BibTeX mode, by Nils Krahnstoever, krahnsto@cse.psu.edu
     based PV-WAVE mode by Ed Stewarton and tex mode by unknown author. -->

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="%" />
	</PROPS>
	<RULES>
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- @... commands -->
		<MARK_FOLLOWING TYPE="KEYWORD2">@</MARK_FOLLOWING>

		<!-- comments -->
		<EOL_SPAN TYPE="COMMENT1">%</EOL_SPAN>

		<SPAN TYPE="MARKUP" DELEGATE="ENTRY">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>
	</RULES>	
	<RULES SET="ENTRY" DEFAULT="MARKUP">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<SPAN TYPE="LITERAL1" DELEGATE="ITEM">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		
		<SPAN TYPE="LITERAL1" DELEGATE="ITEM">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">,</SEQ>

		<KEYWORDS IGNORE_CASE="TRUE">
		<KEYWORD1>address</KEYWORD1>
		<KEYWORD1>annote</KEYWORD1>
		<KEYWORD1>author</KEYWORD1>
		<KEYWORD1>title</KEYWORD1>
		<KEYWORD1>type</KEYWORD1>
		<KEYWORD1>abstract</KEYWORD1>
		<KEYWORD1>volume</KEYWORD1>
		<KEYWORD1>pages</KEYWORD1>
		<KEYWORD1>number</KEYWORD1>
		<KEYWORD1>note</KEYWORD1>
		<KEYWORD1>key</KEYWORD1>
		<KEYWORD1>organization</KEYWORD1>
		<KEYWORD1>school</KEYWORD1>
		<KEYWORD1>series</KEYWORD1>
		<KEYWORD1>chapter</KEYWORD1>
		<KEYWORD1>month</KEYWORD1>
		<KEYWORD1>department</KEYWORD1>
		<KEYWORD1>keywords</KEYWORD1>
		<KEYWORD1>howpublished</KEYWORD1>
		<KEYWORD1>institution</KEYWORD1>
		<KEYWORD1>journal</KEYWORD1>
		<KEYWORD1>publisher</KEYWORD1>
		<KEYWORD1>editon</KEYWORD1>
		<KEYWORD1>editor</KEYWORD1>
		<KEYWORD1>year</KEYWORD1>
		<KEYWORD1>booktitle</KEYWORD1>
		</KEYWORDS>
	</RULES>
	<RULES SET="ITEM" DEFAULT="LITERAL1">
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>			
	</RULES>
</MODE>

=== albfan/jEdit/tags/jedit-4-2-pre10/modes/moin.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="##" />
		<PROPERTY NAME="wrap" VALUE="soft" />
	</PROPS>
	<RULES ESCAPE="\" HIGHLIGHT_DIGITS="FALSE" IGNORE_CASE="FALSE">

		<!-- comment -->
		<EOL_SPAN TYPE="COMMENT1">##</EOL_SPAN>

		<!-- directive -->
		<EOL_SPAN TYPE="KEYWORD2">#pragma</EOL_SPAN>

		<!-- macro -->
		<SPAN TYPE="KEYWORD4">
			<BEGIN>[[</BEGIN>
			<END>]]</END>
		</SPAN>

		<!-- term definition -->
		<SEQ_REGEXP
			HASH_CHAR=' '
			AT_LINE_START='TRUE'
			TYPE="LABEL"
		>\s+\w[[:alnum:][:blank:]]+::</SEQ_REGEXP>

		<!-- smileys -->
		<!-- not on by default because it slows things down a bit
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\sB\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:\)\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\;\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:D\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\%lt;\:\(\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\sX\-\(\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:o\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:\(\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\/\!\\\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\%lt;\!\&gt;\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\(\!\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:\-\?\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\:\&gt;\:\&gt;\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\%\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\@\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\|\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\;\)\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\(\.\/\)\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\{OK\}\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\{X\}\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\{i\}\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\{1\}\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\{2\}\s</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR=' ' AT_LINE_START='FALSE' TYPE="LITERAL3">\s\{3\}\s</SEQ_REGEXP>
		-->

		<!-- code or literal -->
		<SPAN TYPE="LITERAL2">
			<BEGIN>{{{</BEGIN>
			<END>}}}</END>
		</SPAN>

		<!-- code or literal -->
		<SPAN TYPE="LITERAL2">
			<BEGIN>`</BEGIN>
			<END>`</END>
		</SPAN>

		<!-- bold or italic -->
		<SEQ_REGEXP
			HASH_CHAR="'"
			TYPE="LITERAL1"
		>('{2,5})[^']+\1[^']</SEQ_REGEXP>

		<!-- horizontal rule -->
		<SEQ_REGEXP
			HASH_CHAR="-"
			TYPE="LITERAL4"
		>-{4,}</SEQ_REGEXP>

		<!-- section header -->
		<SPAN_REGEXP 
			HASH_CHAR="=" 
			TYPE="KEYWORD1" 
			AT_LINE_START="TRUE"
		>
			<BEGIN>(={1,5}) </BEGIN>
			<END> $1</END>
		</SPAN_REGEXP>

		<!-- implicit WikiWords - a bit of a hack, but I can't think of a better way... -->
		<SEQ_REGEXP HASH_CHAR="A" AT_WORD_START="TRUE" TYPE="KEYWORD2">A[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="B" AT_WORD_START="TRUE" TYPE="KEYWORD2">B[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="C" AT_WORD_START="TRUE" TYPE="KEYWORD2">C[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="D" AT_WORD_START="TRUE" TYPE="KEYWORD2">D[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="E" AT_WORD_START="TRUE" TYPE="KEYWORD2">E[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="F" AT_WORD_START="TRUE" TYPE="KEYWORD2">F[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="G" AT_WORD_START="TRUE" TYPE="KEYWORD2">G[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="H" AT_WORD_START="TRUE" TYPE="KEYWORD2">H[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="I" AT_WORD_START="TRUE" TYPE="KEYWORD2">I[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="J" AT_WORD_START="TRUE" TYPE="KEYWORD2">J[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="K" AT_WORD_START="TRUE" TYPE="KEYWORD2">K[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="L" AT_WORD_START="TRUE" TYPE="KEYWORD2">L[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="M" AT_WORD_START="TRUE" TYPE="KEYWORD2">M[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="N" AT_WORD_START="TRUE" TYPE="KEYWORD2">N[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="O" AT_WORD_START="TRUE" TYPE="KEYWORD2">O[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="P" AT_WORD_START="TRUE" TYPE="KEYWORD2">P[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="Q" AT_WORD_START="TRUE" TYPE="KEYWORD2">Q[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="R" AT_WORD_START="TRUE" TYPE="KEYWORD2">R[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="S" AT_WORD_START="TRUE" TYPE="KEYWORD2">S[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="T" AT_WORD_START="TRUE" TYPE="KEYWORD2">T[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="U" AT_WORD_START="TRUE" TYPE="KEYWORD2">U[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="V" AT_WORD_START="TRUE" TYPE="KEYWORD2">V[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="W" AT_WORD_START="TRUE" TYPE="KEYWORD2">W[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="X" AT_WORD_START="TRUE" TYPE="KEYWORD2">X[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="Y" AT_WORD_START="TRUE" TYPE="KEYWORD2">Y[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>
		<SEQ_REGEXP HASH_CHAR="Z" AT_WORD_START="TRUE" TYPE="KEYWORD2">Z[a-z]+[A-Z][a-zA-Z]+</SEQ_REGEXP>

		<!-- explicit WikiWord -->
		<SPAN TYPE="KEYWORD2">
			<BEGIN>[&quot;</BEGIN>
			<END>&quot;]</END>
		</SPAN>

		<!-- url -->
		<SPAN TYPE="KEYWORD3">
			<BEGIN>[</BEGIN>
			<END>]</END>
		</SPAN>

	</RULES>
</MODE>
