=== albfan/jEdit/tags/jedit-4-2-pre3/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | COMMENT3 | COMMENT4 |
	DIGIT | FUNCTION | INVALID | KEYWORD1 | KEYWORD2 | KEYWORD3 | KEYWORD4 |
	LABEL | LITERAL1 | LITERAL2 | LITERAL3 | LITERAL4 | MARKUP | OPERATOR )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-type 'TYPE %tokens; "NULL"' >
<!ENTITY % att-position-mix 'AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"
	NO_ESCAPE %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( IMPORT | TERMINATE | SEQ | SEQ_REGEXP | SPAN
	| SPAN_REGEXP | EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- IMPORT element -->
<!ELEMENT IMPORT EMPTY >
<!ATTLIST IMPORT DELEGATE CDATA #REQUIRED >

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ATTLIST BEGIN %att-position-mix; >
<!ELEMENT END ( #PCDATA ) >
<!ATTLIST END %att-position-mix; >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS (%tokens;)+ >

<!-- KEYWORDS children -->
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT COMMENT3 ( #PCDATA ) >
<!ELEMENT COMMENT4 ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT KEYWORD4 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LITERAL3 ( #PCDATA ) >
<!ELEMENT LITERAL4 ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== albfan/jEdit/tags/jedit-4-0-pre9/modes/actionscript.xml
<?xml version="1.0"?>
<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!--
	ActionScript mode by Ben Glazer <ben@enspire.com>
	Adapted from JavaScript mode by Andre Kaplan
-->
<MODE>
	<PROPS>
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<!-- the ; hack is there so that stuff like if(bob) fred();
		     does not indent the next line -->
		<PROPERTY NAME="indentPrevLine" VALUE="\s*(if|while)\s*(|else|case|default:)[^;]*|for\s*\(.*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="commentStart" VALUE="/*" />
		<PROPERTY NAME="commentEnd" VALUE="*/" />
		<PROPERTY NAME="lineComment" VALUE="//" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />
	</PROPS>

	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<SPAN TYPE="COMMENT1">
			<BEGIN>/*</BEGIN>
			<END>*/</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<EOL_SPAN TYPE="COMMENT1">//</EOL_SPAN>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">(</SEQ>

		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">.</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="OPERATOR">,</SEQ>
		<SEQ TYPE="OPERATOR">;</SEQ>
		<SEQ TYPE="OPERATOR">]</SEQ>
		<SEQ TYPE="OPERATOR">[</SEQ>
		<SEQ TYPE="OPERATOR">?</SEQ>
		<MARK_PREVIOUS TYPE="LABEL" EXCLUDE_MATCH="TRUE"
			AT_LINE_START="TRUE">:</MARK_PREVIOUS>
		<SEQ TYPE="OPERATOR">:</SEQ>

		<KEYWORDS IGNORE_CASE="FALSE">
			<!-- ActionScript's reserved words (see AS:TDG p.332) -->
			<KEYWORD1>add</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>and</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>delete</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>eq</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>function</KEYWORD1>
			<KEYWORD1>ge</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>gt</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>ifFrameLoaded</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>le</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>lt</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>ne</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>new</KEYWORD1>
			<KEYWORD1>not</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>on</KEYWORD1>
			<KEYWORD1>onClipEvent</KEYWORD1>
			<KEYWORD1>or</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>return</KEYWORD1>
			<LITERAL2>this</LITERAL2>
			<KEYWORD1>tellTarget</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>typeof</KEYWORD1>
			<KEYWORD1>var</KEYWORD1>
			<KEYWORD3>void</KEYWORD3>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>with</KEYWORD1>

			<!-- Built-in objects (good idea not to use these names!)-->
			<KEYWORD3>Array</KEYWORD3>
			<KEYWORD3>Boolean</KEYWORD3>
			<KEYWORD3>Color</KEYWORD3>
			<KEYWORD3>Date</KEYWORD3>
			<KEYWORD3>Function</KEYWORD3>
			<KEYWORD3>Key</KEYWORD3>
			<KEYWORD3>MovieClip</KEYWORD3>
			<KEYWORD3>Math</KEYWORD3>
			<KEYWORD3>Mouse</KEYWORD3>
			<KEYWORD3>Number</KEYWORD3>
			<KEYWORD3>Object</KEYWORD3>
			<KEYWORD3>Selection</KEYWORD3>
			<KEYWORD3>Sound</KEYWORD3>
			<KEYWORD3>String</KEYWORD3>
			<KEYWORD3>XML</KEYWORD3>
			<KEYWORD3>XMLNode</KEYWORD3>
			<KEYWORD3>XMLSocket</KEYWORD3>

			<!-- Literals -->
			<LITERAL2>NaN</LITERAL2>
			<LITERAL2>Infinity</LITERAL2>
			<LITERAL2>false</LITERAL2>
			<LITERAL2>null</LITERAL2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>undefined</LITERAL2>

			<!-- Global functions -->
			<LITERAL2>Boolean</LITERAL2>
			<LITERAL2>call</LITERAL2>
			<LITERAL2>Date</LITERAL2>
			<LITERAL2>duplicateMovieClip</LITERAL2>
			<LITERAL2>escape</LITERAL2>
			<LITERAL2>eval</LITERAL2>
			<LITERAL2>fscommand</LITERAL2>
			<LITERAL2>getProperty</LITERAL2>
			<LITERAL2>getTimer</LITERAL2>
			<LITERAL2>getURL</LITERAL2>
			<LITERAL2>getVersion</LITERAL2>
			<LITERAL2>gotoAndPlay</LITERAL2>
			<LITERAL2>gotoAndStop</LITERAL2>
			<LITERAL2>#include</LITERAL2>
			<LITERAL2>int</LITERAL2>   <!-- deprecated -->
			<LITERAL2>isFinite</LITERAL2>
			<LITERAL2>isNaN</LITERAL2>
			<LITERAL2>loadMovie</LITERAL2>
			<LITERAL2>loadMovieNum</LITERAL2>
			<LITERAL2>loadVariables</LITERAL2>
			<LITERAL2>loadVariablesNum</LITERAL2>
			<LITERAL2>maxscroll</LITERAL2>
			<LITERAL2>newline</LITERAL2>
			<LITERAL2>nextFrame</LITERAL2>
			<LITERAL2>nextScene</LITERAL2>
			<LITERAL2>Number</LITERAL2>
			<LITERAL2>parseFloat</LITERAL2>
			<LITERAL2>parseInt</LITERAL2>
			<LITERAL2>play</LITERAL2>
			<LITERAL2>prevFrame</LITERAL2>
			<LITERAL2>prevScene</LITERAL2>
			<LITERAL2>print</LITERAL2>
			<LITERAL2>printAsBitmap</LITERAL2>
			<LITERAL2>printAsBitmapNum</LITERAL2>
			<LITERAL2>printNum</LITERAL2>
			<LITERAL2>random</LITERAL2>   <!-- deprecated -->
			<LITERAL2>removeMovieClip</LITERAL2>
			<LITERAL2>scroll</LITERAL2>
			<LITERAL2>setProperty</LITERAL2>
			<LITERAL2>startDrag</LITERAL2>
			<LITERAL2>stop</LITERAL2>
			<LITERAL2>stopAllSounds</LITERAL2>
			<LITERAL2>stopDrag</LITERAL2>
			<LITERAL2>String</LITERAL2>
			<LITERAL2>targetPath</LITERAL2>
			<LITERAL2>tellTarget</LITERAL2>   <!-- deprecated -->
			<LITERAL2>toggleHighQuality</LITERAL2>   <!-- deprecated -->
			<LITERAL2>trace</LITERAL2>
			<LITERAL2>unescape</LITERAL2>
			<LITERAL2>unloadMovie</LITERAL2>
			<LITERAL2>unloadMovieNum</LITERAL2>
			<LITERAL2>updateAfterEvent</LITERAL2>

			<!--ECMAScript keywords-->
			<!-- Reserved for future use 
				(some are already used in some Javascript Engines) 
			-->
			<KEYWORD1>abstract</KEYWORD1>
			<KEYWORD3>boolean</KEYWORD3>
			<KEYWORD3>byte</KEYWORD3>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>catch</KEYWORD1>
			<KEYWORD3>char</KEYWORD3>
			<KEYWORD1>class</KEYWORD1>
			<KEYWORD1>const</KEYWORD1>
			<KEYWORD1>debugger</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>

			<KEYWORD3>double</KEYWORD3>
			<KEYWORD1>enum</KEYWORD1>
			<KEYWORD2>export</KEYWORD2>
			<KEYWORD1>extends</KEYWORD1>
			<KEYWORD1>final</KEYWORD1>
			<KEYWORD1>finally</KEYWORD1>
			<KEYWORD3>float</KEYWORD3>
			<KEYWORD1>goto</KEYWORD1>
			<KEYWORD1>implements</KEYWORD1>

			<KEYWORD2>import</KEYWORD2>
			<KEYWORD1>instanceof</KEYWORD1>
			<KEYWORD3>int</KEYWORD3>
			<KEYWORD1>interface</KEYWORD1>
			<KEYWORD3>long</KEYWORD3>
			<KEYWORD1>native</KEYWORD1>
			<KEYWORD2>package</KEYWORD2>
			<KEYWORD1>private</KEYWORD1>
			<KEYWORD1>protected</KEYWORD1>
			<KEYWORD1>public</KEYWORD1>

			<KEYWORD3>short</KEYWORD3>
			<KEYWORD1>static</KEYWORD1>
			<LITERAL2>super</LITERAL2>
			<KEYWORD1>switch</KEYWORD1>
			<KEYWORD1>synchronized</KEYWORD1>
			<KEYWORD1>throw</KEYWORD1>
			<KEYWORD1>throws</KEYWORD1>
			<KEYWORD1>transient</KEYWORD1>
			<KEYWORD1>try</KEYWORD1>
			<KEYWORD1>volatile</KEYWORD1>
		</KEYWORDS>
	</RULES>
</MODE>

=== albfan/jEdit/tags/jedit-4-1-pre6/modes/pike.xml
<?xml version="1.0"?>

<!-- Pike mode, contributed by Marco G"otze, <gomar@gmx.net> -->

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
  <PROPS>
    <PROPERTY NAME="indentOpenBrackets" VALUE="{[<" />
    <PROPERTY NAME="indentCloseBrackets" VALUE="}]>" />
    <PROPERTY NAME="indentPrevLine"
      VALUE="\s*(((if|(for(each)?)|while|catch|gauge)\s*\(|(do|else)\s*|else\s+if\s*\()[^{;]*)" />
    <!-- set this to 'true' if you want to use GNU coding style -->
    <PROPERTY NAME="doubleBracketIndent" VALUE="false" />
    <PROPERTY NAME="commentStart" VALUE="/*" />
    <PROPERTY NAME="commentEnd" VALUE="*/" />
    <PROPERTY NAME="lineComment" VALUE="//" />
    <PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*`" />
  </PROPS>
  <RULES ESCAPE="\"
    IGNORE_CASE="FALSE"
    HIGHLIGHT_DIGITS="TRUE"
    DIGIT_RE="(0x[[:xdigit:]]+|[[:digit]]+|0[bB][01]+)[lLdDfF]?">

    <!-- comments -->
    <SPAN TYPE="COMMENT1" DELEGATE="COMMENT">
      <BEGIN>/*</BEGIN>
      <END>*/</END>
    </SPAN>
    <SEQ TYPE="INVALID">*/</SEQ>
    <EOL_SPAN TYPE="COMMENT1" DELEGATE="COMMENT">//</EOL_SPAN>

    <!-- string, char literals -->
    <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE" DELEGATE="STRING_LITERAL">
      <BEGIN>"</BEGIN>
      <END>"</END>
    </SPAN>
    <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
      <BEGIN>'</BEGIN>
      <END>'</END>
    </SPAN>

    <!-- preprocessor statements -->
    <SEQ_REGEXP TYPE="KEYWORD2"
      HASH_CHAR="#"
      AT_LINE_START="TRUE"
    >#.*?(?=($|/\*|//))</SEQ_REGEXP>

    <!-- operators -->
    <SEQ TYPE="OPERATOR">({</SEQ>
    <SEQ TYPE="OPERATOR">})</SEQ>
    <SEQ TYPE="OPERATOR">([</SEQ>
    <SEQ TYPE="OPERATOR">])</SEQ>
    <SEQ TYPE="OPERATOR">(&lt;</SEQ>
    <SEQ TYPE="OPERATOR">&gt;)</SEQ>
    <SEQ TYPE="OPERATOR">=</SEQ>
    <SEQ TYPE="OPERATOR">!</SEQ>
    <SEQ TYPE="OPERATOR">+</SEQ>
    <SEQ TYPE="OPERATOR">-</SEQ>
    <SEQ TYPE="OPERATOR">/</SEQ>
    <SEQ TYPE="OPERATOR">*</SEQ>
    <SEQ TYPE="OPERATOR">&gt;</SEQ>
    <SEQ TYPE="OPERATOR">&lt;</SEQ>
    <SEQ TYPE="OPERATOR">%</SEQ>
    <SEQ TYPE="OPERATOR">&amp;</SEQ>
    <SEQ TYPE="OPERATOR">|</SEQ>
    <SEQ TYPE="OPERATOR">^</SEQ>
    <SEQ TYPE="OPERATOR">~</SEQ>
    <SEQ TYPE="OPERATOR">@</SEQ>
    <SEQ TYPE="OPERATOR">`</SEQ>
    <SEQ TYPE="OPERATOR">.</SEQ>

    <!-- function calls -->
    <MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

    <KEYWORDS>
      <!-- type modifiers -->
      <KEYWORD1>constant</KEYWORD1>
      <KEYWORD1>extern</KEYWORD1>
      <KEYWORD1>final</KEYWORD1>
      <KEYWORD1>inline</KEYWORD1>
      <KEYWORD1>local</KEYWORD1>
      <KEYWORD1>nomask</KEYWORD1>
      <KEYWORD1>optional</KEYWORD1>
      <KEYWORD1>private</KEYWORD1>
      <KEYWORD1>protected</KEYWORD1>
      <KEYWORD1>public</KEYWORD1>
      <KEYWORD1>static</KEYWORD1>
      <KEYWORD1>variant</KEYWORD1>

      <!-- types -->
      <KEYWORD3>array</KEYWORD3>
      <KEYWORD3>class</KEYWORD3>
      <KEYWORD3>float</KEYWORD3>
      <KEYWORD3>function</KEYWORD3>
      <KEYWORD3>int</KEYWORD3>
      <KEYWORD3>mapping</KEYWORD3>
      <KEYWORD3>mixed</KEYWORD3>
      <KEYWORD3>multiset</KEYWORD3>
      <KEYWORD3>object</KEYWORD3>
      <KEYWORD3>program</KEYWORD3>
      <KEYWORD3>string</KEYWORD3>
      <KEYWORD3>void</KEYWORD3>

      <!-- flow control and block-introducing keywords -->
      <KEYWORD1>break</KEYWORD1>
      <KEYWORD1>case</KEYWORD1>
      <KEYWORD1>catch</KEYWORD1>
      <KEYWORD1>continue</KEYWORD1>
      <KEYWORD1>default</KEYWORD1>
      <KEYWORD1>do</KEYWORD1>
      <KEYWORD1>else</KEYWORD1>
      <KEYWORD1>for</KEYWORD1>
      <KEYWORD1>foreach</KEYWORD1>
      <KEYWORD1>gauge</KEYWORD1>
      <KEYWORD1>if</KEYWORD1>
      <KEYWORD1>lambda</KEYWORD1>
      <KEYWORD1>return</KEYWORD1>
      <KEYWORD1>sscanf</KEYWORD1>
      <KEYWORD1>switch</KEYWORD1>
      <KEYWORD1>while</KEYWORD1>

      <!-- special instructions -->
      <KEYWORD2>import</KEYWORD2>
      <KEYWORD2>inherit</KEYWORD2>
    </KEYWORDS>
  </RULES>

  <RULES SET="COMMENT" IGNORE_CASE="FALSE" DEFAULT="COMMENT1">
    <KEYWORDS>
      <COMMENT2>FIXME</COMMENT2>
      <COMMENT2>XXX</COMMENT2>
    </KEYWORDS>
  </RULES>

  <RULES SET="STRING_LITERAL" IGNORE_CASE="TRUE" DEFAULT="LITERAL1">
    <SEQ_REGEXP TYPE="LITERAL2" HASH_CHAR="%"
      >%([^ a-z]*[a-z]|\[[^\]]*\])</SEQ_REGEXP>
    <SEQ_REGEXP TYPE="COMMENT2" HASH_CHAR="D">DEBUG:</SEQ_REGEXP>
  </RULES>
</MODE>

=== albfan/jEdit/tags/jedit-4-1-pre8/modes/icon.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- Icon mode by Silas Smith (smiths@cs.arizona.edu) -->
<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="#" />
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="FALSE" 
	    HIGHLIGHT_DIGITS="TRUE" 
	    DIGIT_RE="(0x[[:xdigit:]]+|[[:digit:]]+(e[[:digit:]]*)?)[lLdDfF]?">
		<!-- comments -->
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>

		<!-- string literals -->
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<!-- cset literals -->
		<SPAN TYPE="LITERAL2" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">~===</SEQ>
		<SEQ TYPE="OPERATOR">===</SEQ>
		<SEQ TYPE="OPERATOR">|||</SEQ> <!-- list concatenation -->
		
		<!-- lexical operators -->
		<SEQ TYPE="OPERATOR">&gt;&gt;=</SEQ> <!-- ">>=" -->
		<SEQ TYPE="OPERATOR">&gt;&gt;</SEQ> <!-- ">>" -->
		<SEQ TYPE="OPERATOR">&lt;&lt;=</SEQ> <!-- "<<=" -->
		<SEQ TYPE="OPERATOR">&lt;&lt;</SEQ> <!-- "<<" -->
		<SEQ TYPE="OPERATOR">~==</SEQ>
		<SEQ TYPE="OPERATOR">==</SEQ>
		<SEQ TYPE="OPERATOR">||</SEQ>
		
		<!-- set operators -->
		<SEQ TYPE="OPERATOR">++</SEQ> <!-- union -->
		<SEQ TYPE="OPERATOR">**</SEQ> <!-- intersection -->
		<SEQ TYPE="OPERATOR">--</SEQ> <!-- difference -->

		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">~=</SEQ>
		<SEQ TYPE="OPERATOR">:=</SEQ>


		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">?</SEQ>
		<SEQ TYPE="OPERATOR">@</SEQ>

		<!-- numerical operators -->
				<!-- NOTE: '*' defined above -->
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		
		<!-- Function calls -->
		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<KEYWORDS>
			<KEYWORD1>break</KEYWORD1> 
			<KEYWORD1>by</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>create</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>end</KEYWORD1>
			<KEYWORD1>every</KEYWORD1>
			<KEYWORD1>fail</KEYWORD1>
			<KEYWORD1>global</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>initial</KEYWORD1>
			<KEYWORD1>invocable</KEYWORD1>
			<KEYWORD1>link</KEYWORD1>
			<KEYWORD1>local</KEYWORD1>
			<KEYWORD1>next</KEYWORD1>
			<KEYWORD1>not</KEYWORD1>
			<KEYWORD1>of</KEYWORD1>
			<KEYWORD1>procedure</KEYWORD1>
			<KEYWORD1>record</KEYWORD1>
			<KEYWORD1>repeat</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>static</KEYWORD1>
			<KEYWORD1>suspend</KEYWORD1>
			<KEYWORD1>then</KEYWORD1>
			<KEYWORD1>to</KEYWORD1>
			<KEYWORD1>until</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			
			<KEYWORD2>&amp;allocated</KEYWORD2>
			<KEYWORD2>&amp;ascii</KEYWORD2>
			<KEYWORD2>&amp;clock</KEYWORD2>
			<KEYWORD2>&amp;collections</KEYWORD2>
			<KEYWORD2>&amp;cset</KEYWORD2>
			<KEYWORD2>&amp;current</KEYWORD2>
			<KEYWORD2>&amp;date</KEYWORD2>
			<KEYWORD2>&amp;dateline</KEYWORD2>
			<KEYWORD2>&amp;digits</KEYWORD2>
			<KEYWORD2>&amp;dump</KEYWORD2>
			<KEYWORD2>&amp;e</KEYWORD2>
			<KEYWORD2>&amp;error</KEYWORD2>
			<KEYWORD2>&amp;errornumber</KEYWORD2>
			<KEYWORD2>&amp;errortext</KEYWORD2>
			<KEYWORD2>&amp;errorvalue</KEYWORD2>
			<KEYWORD2>&amp;errout</KEYWORD2>
			<KEYWORD2>&amp;fail</KEYWORD2>
			<KEYWORD2>&amp;features</KEYWORD2>
			<KEYWORD2>&amp;file</KEYWORD2>
			<KEYWORD2>&amp;host</KEYWORD2>
			<KEYWORD2>&amp;input</KEYWORD2>
			<KEYWORD2>&amp;lcase</KEYWORD2>
			<KEYWORD2>&amp;letters</KEYWORD2>
			<KEYWORD2>&amp;level</KEYWORD2>
			<KEYWORD2>&amp;line</KEYWORD2>
			<KEYWORD2>&amp;main</KEYWORD2>
			<KEYWORD2>&amp;null</KEYWORD2>
			<KEYWORD2>&amp;output</KEYWORD2>
			<KEYWORD2>&amp;phi</KEYWORD2>
			<KEYWORD2>&amp;pi</KEYWORD2>
			<KEYWORD2>&amp;pos</KEYWORD2>
			<KEYWORD2>&amp;progname</KEYWORD2>
			<KEYWORD2>&amp;random</KEYWORD2>
			<KEYWORD2>&amp;regions</KEYWORD2> 
			<KEYWORD2>&amp;source</KEYWORD2>
			<KEYWORD2>&amp;storage</KEYWORD2>
			<KEYWORD2>&amp;subject</KEYWORD2>
			<KEYWORD2>&amp;time</KEYWORD2>
			<KEYWORD2>&amp;trace</KEYWORD2>
			<KEYWORD2>&amp;ucase</KEYWORD2>
			<KEYWORD2>&amp;version</KEYWORD2>

			<!-- preprocessor directives -->
			<KEYWORD2>$define</KEYWORD2>
			<KEYWORD2>$else</KEYWORD2>
			<KEYWORD2>$endif</KEYWORD2>
			<KEYWORD2>$error</KEYWORD2>
			<KEYWORD2>$ifdef</KEYWORD2>
			<KEYWORD2>$ifndef</KEYWORD2>
			<KEYWORD2>$include</KEYWORD2>
			<KEYWORD2>$line</KEYWORD2>
			<KEYWORD2>$undef</KEYWORD2>
			
			<!-- predefined prepocessor symbols -->
			<KEYWORD2>_MACINTOSH</KEYWORD2>
			<KEYWORD2>_MS_WINDOWS_NT</KEYWORD2>
			<KEYWORD2>_MS_WINDOWS</KEYWORD2>
			<KEYWORD2>_MSDOS_386</KEYWORD2>
			<KEYWORD2>_MSDOS</KEYWORD2>
			<KEYWORD2>_OS2</KEYWORD2>
			<KEYWORD2>_PIPES</KEYWORD2>
			<KEYWORD2>_PRESENTATION_MGR</KEYWORD2>
			<KEYWORD2>_SYSTEM_FUNCTION</KEYWORD2>
			<KEYWORD2>_UNIX</KEYWORD2>
			<KEYWORD2>_VMS</KEYWORD2>
			<KEYWORD2>_WINDOW_FUNCTIONS</KEYWORD2>
			<KEYWORD2>_X_WINDOW_SYSTEM</KEYWORD2>
						
			<KEYWORD3>coï¿½expression</KEYWORD3>
			<KEYWORD3>cset</KEYWORD3>
			<KEYWORD3>file</KEYWORD3>
			<KEYWORD3>integer</KEYWORD3>
			<KEYWORD3>list</KEYWORD3>
			<KEYWORD3>null</KEYWORD3>
			<KEYWORD3>procedure</KEYWORD3>
			<KEYWORD3>real</KEYWORD3>
			<KEYWORD3>set</KEYWORD3>
			<KEYWORD3>string</KEYWORD3>
			<KEYWORD3>table</KEYWORD3>
			<KEYWORD3>window</KEYWORD3>
		</KEYWORDS>
	</RULES>
</MODE>

=== albfan/jEdit/tags/jedit-4-2-final/modes/c.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
    <PROPS>
        <PROPERTY NAME="commentStart" VALUE="/*" />
        <PROPERTY NAME="commentEnd" VALUE="*/" />
        <PROPERTY NAME="lineComment" VALUE="//" />
        <PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />

        <!-- Auto indent -->
        <PROPERTY NAME="indentOpenBrackets" VALUE="{" />
        <PROPERTY NAME="indentCloseBrackets" VALUE="}" />
        <PROPERTY NAME="indentNextLine"
            VALUE="\s*(((if|while)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
        <!-- set this to 'true' if you want to use GNU coding style -->
        <PROPERTY NAME="doubleBracketIndent" VALUE="false" />
        <PROPERTY NAME="lineUpClosingBracket" VALUE="true" />
    </PROPS>
    <RULES ESCAPE="\"
        IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE"
        DIGIT_RE="(0x[[:xdigit:]]+[lL]?|[[:digit:]]+(e[[:digit:]]*)?[lLdDfF]?)">

        <!-- Doxygen comment, Javadoc style -->
        <SPAN TYPE="COMMENT3" DELEGATE="doxygen::DOXYGEN">
            <BEGIN>/**</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- Doxygen comment, Qt style -->
        <SPAN TYPE="COMMENT3" DELEGATE="doxygen::DOXYGEN">
            <BEGIN>/*!</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- C style comment -->
        <SPAN TYPE="COMMENT1">
            <BEGIN>/*</BEGIN>
            <END>*/</END>
        </SPAN>

        <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
            <BEGIN>"</BEGIN>
            <END>"</END>
        </SPAN>
        <SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
            <BEGIN>'</BEGIN>
            <END>'</END>
        </SPAN>

        <!-- preprocessor statements -->
        <SEQ TYPE="KEYWORD2">##</SEQ>
        <EOL_SPAN TYPE="KEYWORD2" DELEGATE="CPP">#</EOL_SPAN>

        <EOL_SPAN TYPE="COMMENT2">//</EOL_SPAN>
        <SEQ TYPE="OPERATOR">=</SEQ>
        <SEQ TYPE="OPERATOR">!</SEQ>
        <SEQ TYPE="OPERATOR">&gt;=</SEQ>
        <SEQ TYPE="OPERATOR">&lt;=</SEQ>
        <SEQ TYPE="OPERATOR">+</SEQ>
        <SEQ TYPE="OPERATOR">-</SEQ>
        <SEQ TYPE="OPERATOR">/</SEQ>

        <SEQ TYPE="OPERATOR">*</SEQ>
        <SEQ TYPE="OPERATOR">&gt;</SEQ>
        <SEQ TYPE="OPERATOR">&lt;</SEQ>
        <SEQ TYPE="OPERATOR">%</SEQ>
        <SEQ TYPE="OPERATOR">&amp;</SEQ>
        <SEQ TYPE="OPERATOR">|</SEQ>
        <SEQ TYPE="OPERATOR">^</SEQ>
        <SEQ TYPE="OPERATOR">~</SEQ>
        <SEQ TYPE="OPERATOR">}</SEQ>
        <SEQ TYPE="OPERATOR">{</SEQ>
        <MARK_PREVIOUS AT_WHITESPACE_END="TRUE"
            EXCLUDE_MATCH="TRUE"
            TYPE="LABEL">:</MARK_PREVIOUS>

        <!-- Function calls -->
        <MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

        <KEYWORDS>
            <KEYWORD3>char</KEYWORD3>
            <KEYWORD3>double</KEYWORD3>
            <KEYWORD3>enum</KEYWORD3>
            <KEYWORD3>float</KEYWORD3>
            <KEYWORD3>int</KEYWORD3>
            <KEYWORD3>long</KEYWORD3>
            <KEYWORD3>short</KEYWORD3>
            <KEYWORD3>signed</KEYWORD3>
            <KEYWORD3>struct</KEYWORD3>
            <KEYWORD3>typedef</KEYWORD3>
            <KEYWORD3>union</KEYWORD3>
            <KEYWORD3>unsigned</KEYWORD3>
            <KEYWORD3>void</KEYWORD3>
            <KEYWORD1>auto</KEYWORD1>
            <KEYWORD1>const</KEYWORD1>
            <KEYWORD1>extern</KEYWORD1>
            <KEYWORD1>register</KEYWORD1>
            <KEYWORD1>static</KEYWORD1>
            <KEYWORD1>volatile</KEYWORD1>
            <KEYWORD1>break</KEYWORD1>
            <KEYWORD1>case</KEYWORD1>
            <KEYWORD1>continue</KEYWORD1>
            <KEYWORD1>default</KEYWORD1>
            <KEYWORD1>do</KEYWORD1>
            <KEYWORD1>else</KEYWORD1>
            <KEYWORD1>for</KEYWORD1>
            <KEYWORD1>goto</KEYWORD1>
            <KEYWORD1>if</KEYWORD1>
            <KEYWORD1>return</KEYWORD1>
            <KEYWORD1>sizeof</KEYWORD1>
            <KEYWORD1>switch</KEYWORD1>
            <KEYWORD1>while</KEYWORD1>
            <KEYWORD2>asm</KEYWORD2>
            <KEYWORD2>asmlinkage</KEYWORD2>
            <KEYWORD2>far</KEYWORD2>
            <KEYWORD2>huge</KEYWORD2>
            <KEYWORD2>inline</KEYWORD2>
            <KEYWORD2>near</KEYWORD2>
            <KEYWORD2>pascal</KEYWORD2>
            <LITERAL2>true</LITERAL2>
            <LITERAL2>false</LITERAL2>
            <LITERAL2>NULL</LITERAL2>
        </KEYWORDS>
    </RULES>

    <RULES SET="CPP" DEFAULT="KEYWORD2" IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE"
        DIGIT_RE="(0x[[:xdigit:]]+[lL]?|[[:digit:]]+(e[[:digit:]]*)?[lLdDfF]?)">
        <!-- C style comment -->
        <SPAN TYPE="COMMENT1">
            <BEGIN>/*</BEGIN>
            <END>*/</END>
        </SPAN>

        <!-- this is a hack so that #include <net/if.h> does not get
             the if highlighted -->
        <EOL_SPAN TYPE="MARKUP" DELEGATE="INCLUDE">include</EOL_SPAN>

        <!-- Directives -->
        <KEYWORDS>
            <MARKUP>assert</MARKUP>
            <MARKUP>define</MARKUP>
            <MARKUP>assert</MARKUP>
            <MARKUP>define</MARKUP>
            <MARKUP>elif</MARKUP>
            <MARKUP>else</MARKUP>
            <MARKUP>endif</MARKUP>
            <MARKUP>error</MARKUP>
            <MARKUP>ident</MARKUP>
            <MARKUP>if</MARKUP>
            <MARKUP>ifdef</MARKUP>
            <MARKUP>ifndef</MARKUP>
            <MARKUP>import</MARKUP>
            <MARKUP>include</MARKUP>
            <MARKUP>include_next</MARKUP>
            <MARKUP>line</MARKUP>
            <MARKUP>pragma</MARKUP>
            <MARKUP>sccs</MARKUP>
            <MARKUP>unassert</MARKUP>
            <MARKUP>undef</MARKUP>
            <MARKUP>warning</MARKUP>
        </KEYWORDS>
    </RULES>

    <RULES SET="INCLUDE" DEFAULT="KEYWORD2" />

</MODE>
